// Multi-language support for TradeBase
const LANGUAGES = {
  en: { name: "English", flag: "🇺🇸" },
  es: { name: "Español", flag: "🇪🇸" },
  fr: { name: "Français", flag: "🇫🇷" },
  de: { name: "Deutsch", flag: "🇩🇪" },
  pt: { name: "Português", flag: "🇵🇹" }
};

const TRANSLATIONS = {
  en: {
    // Common
    "common.back": "Back",
    
    // Auth
    "auth.login": "Log In",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.create_account": "Create Account",
    "auth.forgot_password": "Forgot password?",
    "auth.view_pricing": "View Pricing & Plans",
    "auth.login_error": "Invalid email or password",
    "auth.signup_error": "Could not create account",
    
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.new_invoice": "New Invoice",
    "nav.invoices": "Invoices",
    "nav.quotes": "Quotes",
    "nav.clients": "Clients",
    "nav.payments": "Payments",
    "nav.inventory": "Inventory",
    "nav.photos": "Photos",
    "nav.calculator": "Cost Calculator",
    "nav.settings": "Settings",
    "nav.referrals": "Referrals",
    
    // Dashboard
    "dashboard.new_invoice": "New Invoice",
    "dashboard.create_invoice": "Create a new invoice with photos & cost helper.",
    "dashboard.quotes": "Quotes",
    "dashboard.quotes_desc": "Draft and track job quotes.",
    "dashboard.clients": "Clients",
    "dashboard.clients_desc": "Save clients once, reuse forever.",
    "dashboard.photos": "Photos",
    "dashboard.photos_desc": "Browse job photos by invoice.",
    "dashboard.invoices": "Invoices",
    "dashboard.invoices_desc": "View and manage past invoices.",
    "dashboard.payments": "Payments",
    "dashboard.payments_desc": "Accept payments & track status.",
    "dashboard.inventory": "Inventory",
    "dashboard.inventory_desc": "Track supplies, materials & stock.",
    "dashboard.calculator": "Cost Calculator",
    "dashboard.calculator_desc": "Materials, hours, markup – done.",
    "dashboard.settings": "Settings",
    "dashboard.settings_desc": "Logo, business info, defaults.",
    "dashboard.referrals": "Referrals",
    "dashboard.referrals_desc": "Share your link, earn 20% for life.",
    
    // Invoice
    "invoice.invoice": "INVOICE",
    "invoice.quote": "QUOTE",
    "invoice.invoice_number": "Invoice #",
    "invoice.quote_number": "Quote #",
    "invoice.date": "Date",
    "invoice.due_date": "Due Date",
    "invoice.client": "Bill To",
    "invoice.description": "Description",
    "invoice.quantity": "Qty",
    "invoice.unit_price": "Unit Price",
    "invoice.total": "Total",
    "invoice.subtotal": "Subtotal",
    "invoice.tax": "Tax",
    "invoice.amount_due": "Amount Due",
    "invoice.notes": "Notes",
    "invoice.payment_terms": "Payment Terms",
    "invoice.thank_you": "Thank you for your business!",
    "invoice.download": "Download",
    "invoice.send": "Send",
    
    // Clients
    "client.clients": "Clients",
    "client.add": "Add Client",
    "client.name_placeholder": "Client name",
    "client.phone_placeholder": "Phone",
    "client.email_placeholder": "Email",
    "client.address_placeholder": "Address",
    
    // Settings
    "settings.title": "Settings & Business Info",
    "settings.settings": "Settings & Business Info",
    "settings.business_name": "Business Name",
    "settings.phone": "Phone",
    "settings.email": "Email",
    "settings.address": "Address",
    "settings.website": "Website",
    "settings.default_tax": "Default Tax %",
    "settings.default_markup": "Default Markup %",
    "settings.footer": "Invoice Footer Text",
    "settings.invoice_footer": "Invoice Footer Text",
    "settings.logo": "Upload Logo",
    "settings.upload_logo": "Upload Logo",
    "settings.save": "Save Settings",
    "settings.language": "Language",
    "settings.invoice_template": "Invoice Template",
    "settings.saved": "Settings saved.",
    
    // Template Chooser
    "template.choose_template": "Choose Invoice Template",
    "template.choose_desc": "Click a template to download your invoice in that style.",
    
    // Inventory
    "inventory.inventory": "Inventory Management",
    "inventory.add_item": "Add Item",
    "inventory.item_name": "Item Name",
    "inventory.description": "Description",
    "inventory.category": "Category",
    "inventory.quantity": "Quantity",
    "inventory.unit_type": "Unit Type",
    "inventory.unit_price": "Unit Price ($)",
    "inventory.low_stock": "Low Stock Threshold",
    "inventory.total_value": "Total Inventory Value",
    "inventory.items_in_stock": "items in stock",
    "inventory.save_item": "Save Item",
    "inventory.delete": "Delete",
    "inventory.no_items": "No inventory items yet",
    "inventory.add_first": "Add Your First Item",
    
    // Payments
    "payments.payment_collection": "Payment Collection",
    "payments.stripe_status": "Stripe Connect Status",
    "payments.active": "Active",
    "payments.not_enabled": "Not Enabled",
    "payments.stats": "Payment Statistics",
    "payments.outstanding": "Outstanding",
    "payments.paid_month": "Paid (This Month)",
    "payments.pending": "Pending",
    "payments.how_it_works": "How It Works",
    
    // Referrals
    "referrals.referrals": "Referrals – 20% For Life",
    "referrals.share": "Share your link. Earn 20% of every monthly payment for everyone you bring in, for as long as they stay subscribed.",
    "referrals.link": "Your referral link",
    "referrals.copy": "Copy",
    "referrals.active": "Active referrals",
    "referrals.month": "This month",
    "referrals.lifetime": "Lifetime earned",
    
    // Trial & Auth
    "trial.banner": "Free trial: X days remaining",
    "trial.subscribe_now": "Subscribe Now",
    "tour.demo": "You're viewing a demo with sample data. Forms are disabled.",
    "tour.exit": "Exit Tour & Subscribe",
  },
  es: {
    "common.back": "Atrás",
    
    "auth.login": "Iniciar sesión",
    "auth.signup": "Registrarse",
    "auth.email": "Correo",
    "auth.password": "Contraseña",
    "auth.create_account": "Crear cuenta",
    "auth.forgot_password": "¿Olvidaste la contraseña?",
    "auth.view_pricing": "Ver precios y planes",
    
    "nav.dashboard": "Panel",
    "nav.new_invoice": "Nueva factura",
    "nav.invoices": "Facturas",
    "nav.quotes": "Presupuestos",
    "nav.clients": "Clientes",
    "nav.payments": "Pagos",
    "nav.inventory": "Inventario",
    "nav.photos": "Fotos",
    "nav.calculator": "Calculadora de costos",
    "nav.settings": "Configuración",
    "nav.referrals": "Referidos",
    
    "dashboard.new_invoice": "Nueva factura",
    "dashboard.create_invoice": "Crea una nueva factura con fotos y ayuda de costos.",
    "dashboard.quotes": "Presupuestos",
    "dashboard.quotes_desc": "Redacta y realiza un seguimiento de presupuestos de trabajos.",
    "dashboard.clients": "Clientes",
    "dashboard.clients_desc": "Guarda clientes una vez, reutiliza siempre.",
    "dashboard.photos": "Fotos",
    "dashboard.photos_desc": "Examina fotos de trabajo por factura.",
    "dashboard.invoices": "Facturas",
    "dashboard.invoices_desc": "Ver y gestionar facturas anteriores.",
    "dashboard.payments": "Pagos",
    "dashboard.payments_desc": "Acepta pagos y realiza un seguimiento del estado.",
    "dashboard.inventory": "Inventario",
    "dashboard.inventory_desc": "Realiza un seguimiento de suministros, materiales y existencias.",
    "dashboard.calculator": "Calculadora",
    "dashboard.calculator_desc": "Materiales, horas, margen – hecho.",
    "dashboard.settings": "Configuración",
    "dashboard.settings_desc": "Logotipo, info empresarial, predeterminados.",
    "dashboard.referrals": "Referidos",
    "dashboard.referrals_desc": "Comparte tu enlace, gana 20% de por vida.",
    
    "invoice.invoice": "FACTURA",
    "invoice.quote": "PRESUPUESTO",
    "invoice.invoice_number": "Factura #",
    "invoice.quote_number": "Presupuesto #",
    "invoice.date": "Fecha",
    "invoice.due_date": "Fecha de vencimiento",
    "invoice.client": "Facturar a",
    "invoice.description": "Descripción",
    "invoice.quantity": "Cantidad",
    "invoice.unit_price": "Precio unitario",
    "invoice.total": "Total",
    "invoice.subtotal": "Subtotal",
    "invoice.tax": "Impuesto",
    "invoice.amount_due": "Cantidad debida",
    "invoice.notes": "Notas",
    "invoice.thank_you": "¡Gracias por tu negocio!",
    "invoice.download": "Descargar",
    "invoice.send": "Enviar",
    
    "client.clients": "Clientes",
    "client.add": "Agregar cliente",
    "client.name_placeholder": "Nombre del cliente",
    "client.phone_placeholder": "Teléfono",
    "client.email_placeholder": "Correo electrónico",
    "client.address_placeholder": "Dirección",
    
    "settings.title": "Configuración e información comercial",
    "settings.settings": "Configuración e información comercial",
    "settings.business_name": "Nombre del negocio",
    "settings.phone": "Teléfono",
    "settings.email": "Correo",
    "settings.address": "Dirección",
    "settings.website": "Sitio web",
    "settings.default_tax": "Impuesto predeterminado %",
    "settings.default_markup": "Margen predeterminado %",
    "settings.footer": "Texto de pie de factura",
    "settings.invoice_footer": "Texto de pie de factura",
    "settings.logo": "Cargar logo",
    "settings.upload_logo": "Cargar logo",
    "settings.save": "Guardar configuración",
    "settings.language": "Idioma",
    "settings.invoice_template": "Plantilla de factura",
    "settings.saved": "Configuración guardada.",
    
    "template.choose_template": "Elegir Plantilla de Factura",
    "template.choose_desc": "Haz clic en una plantilla para descargar tu factura en ese estilo.",
    
    "inventory.inventory": "Gestión de inventario",
    "inventory.add_item": "Agregar artículo",
    "inventory.item_name": "Nombre del artículo",
    "inventory.description": "Descripción",
    "inventory.category": "Categoría",
    "inventory.quantity": "Cantidad",
    "inventory.unit_type": "Tipo de unidad",
    "inventory.unit_price": "Precio unitario ($)",
    "inventory.low_stock": "Umbral de bajo stock",
    "inventory.total_value": "Valor total del inventario",
    "inventory.items_in_stock": "artículos en stock",
    "inventory.save_item": "Guardar artículo",
    "inventory.delete": "Eliminar",
    "inventory.no_items": "Sin artículos de inventario aún",
    "inventory.add_first": "Agregar tu primer artículo",
    
    "payments.payment_collection": "Cobro de pagos",
    "payments.stripe_status": "Estado de Stripe Connect",
    "payments.active": "Activo",
    "payments.not_enabled": "No habilitado",
    "payments.stats": "Estadísticas de pago",
    "payments.outstanding": "Pendiente",
    "payments.paid_month": "Pagado (este mes)",
    "payments.pending": "En espera",
    "payments.how_it_works": "Cómo funciona",
    
    "referrals.referrals": "Referidos – 20% de por vida",
    "referrals.share": "Comparte tu enlace. Gana el 20% de cada pago mensual de todos los que traigas, mientras permanezcan suscritos.",
    "referrals.link": "Tu enlace de referencia",
    "referrals.copy": "Copiar",
    "referrals.active": "Referidos activos",
    "referrals.month": "Este mes",
    "referrals.lifetime": "Ganancia de por vida",
    
    "trial.banner": "Prueba gratuita: X días restantes",
    "trial.subscribe_now": "Suscribirse ahora",
    "tour.demo": "Estás viendo una demostración con datos de ejemplo. Los formularios están deshabilitados.",
    "tour.exit": "Salir de la demostración y suscribirse",
  },
  fr: {
    "common.back": "Retour",
    
    "auth.login": "Connexion",
    "auth.signup": "Inscription",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.create_account": "Créer un compte",
    "auth.forgot_password": "Mot de passe oublié?",
    "auth.view_pricing": "Voir les tarifs et plans",
    
    "nav.dashboard": "Tableau de bord",
    "nav.new_invoice": "Nouvelle facture",
    "nav.invoices": "Factures",
    "nav.quotes": "Devis",
    "nav.clients": "Clients",
    "nav.payments": "Paiements",
    "nav.inventory": "Inventaire",
    "nav.photos": "Photos",
    "nav.calculator": "Calculatrice de coûts",
    "nav.settings": "Paramètres",
    "nav.referrals": "Parrainages",
    
    "dashboard.new_invoice": "Nouvelle facture",
    "dashboard.create_invoice": "Créez une nouvelle facture avec photos et aide aux coûts.",
    "dashboard.quotes": "Devis",
    "dashboard.quotes_desc": "Rédigez et suivez les devis de travaux.",
    "dashboard.clients": "Clients",
    "dashboard.clients_desc": "Enregistrez les clients une fois, réutilisez toujours.",
    "dashboard.photos": "Photos",
    "dashboard.photos_desc": "Parcourez les photos de travaux par facture.",
    "dashboard.invoices": "Factures",
    "dashboard.invoices_desc": "Afficher et gérer les factures passées.",
    "dashboard.payments": "Paiements",
    "dashboard.payments_desc": "Acceptez les paiements et suivez le statut.",
    "dashboard.inventory": "Inventaire",
    "dashboard.inventory_desc": "Suivez les fournitures, matériaux et stock.",
    "dashboard.calculator": "Calculatrice",
    "dashboard.calculator_desc": "Matériaux, heures, marge – terminé.",
    "dashboard.settings": "Paramètres",
    "dashboard.settings_desc": "Logo, infos entreprise, défauts.",
    "dashboard.referrals": "Parrainages",
    "dashboard.referrals_desc": "Partagez votre lien, gagnez 20% à vie.",
    
    "invoice.invoice": "FACTURE",
    "invoice.quote": "DEVIS",
    "invoice.invoice_number": "Facture #",
    "invoice.quote_number": "Devis #",
    "invoice.date": "Date",
    "invoice.due_date": "Date d'échéance",
    "invoice.client": "Facturer à",
    "invoice.description": "Description",
    "invoice.quantity": "Qté",
    "invoice.unit_price": "Prix unitaire",
    "invoice.total": "Total",
    "invoice.subtotal": "Sous-total",
    "invoice.tax": "Taxe",
    "invoice.amount_due": "Montant dû",
    "invoice.notes": "Notes",
    "invoice.thank_you": "Merci pour votre confiance!",
    "invoice.download": "Télécharger",
    "invoice.send": "Envoyer",
    
    "client.clients": "Clients",
    "client.add": "Ajouter un client",
    "client.name_placeholder": "Nom du client",
    "client.phone_placeholder": "Téléphone",
    "client.email_placeholder": "Email",
    "client.address_placeholder": "Adresse",
    
    "settings.title": "Paramètres et informations commerciales",
    "settings.settings": "Paramètres et informations commerciales",
    "settings.business_name": "Nom de l'entreprise",
    "settings.phone": "Téléphone",
    "settings.email": "Email",
    "settings.address": "Adresse",
    "settings.website": "Site web",
    "settings.default_tax": "Taxe par défaut %",
    "settings.default_markup": "Marge par défaut %",
    "settings.footer": "Texte de pied de page de facture",
    "settings.invoice_footer": "Texte de pied de page de facture",
    "settings.logo": "Charger le logo",
    "settings.upload_logo": "Charger le logo",
    "settings.save": "Enregistrer les paramètres",
    "settings.language": "Langue",
    "settings.invoice_template": "Modèle de facture",
    "settings.saved": "Paramètres enregistrés.",
    
    "template.choose_template": "Choisir un Modèle de Facture",
    "template.choose_desc": "Cliquez sur un modèle pour télécharger votre facture dans ce style.",
    
    "inventory.inventory": "Gestion de l'inventaire",
    "inventory.add_item": "Ajouter un article",
    "inventory.item_name": "Nom de l'article",
    "inventory.description": "Description",
    "inventory.category": "Catégorie",
    "inventory.quantity": "Quantité",
    "inventory.unit_type": "Type d'unité",
    "inventory.unit_price": "Prix unitaire ($)",
    "inventory.low_stock": "Seuil de stock faible",
    "inventory.total_value": "Valeur totale de l'inventaire",
    "inventory.items_in_stock": "articles en stock",
    "inventory.save_item": "Enregistrer l'article",
    "inventory.delete": "Supprimer",
    "inventory.no_items": "Pas encore d'articles d'inventaire",
    "inventory.add_first": "Ajouter votre premier article",
    
    "payments.payment_collection": "Recouvrement des paiements",
    "payments.stripe_status": "Statut de Stripe Connect",
    "payments.active": "Actif",
    "payments.not_enabled": "Non activé",
    "payments.stats": "Statistiques de paiement",
    "payments.outstanding": "Impayé",
    "payments.paid_month": "Payé (ce mois)",
    "payments.pending": "En attente",
    "payments.how_it_works": "Comment ça marche",
    
    "referrals.referrals": "Parrainages – 20% à vie",
    "referrals.share": "Partagez votre lien. Gagnez 20% de chaque paiement mensuel de tous ceux que vous apportez, tant qu'ils restent abonnés.",
    "referrals.link": "Votre lien de parrainage",
    "referrals.copy": "Copier",
    "referrals.active": "Parrainages actifs",
    "referrals.month": "Ce mois",
    "referrals.lifetime": "Gains à vie",
    
    "trial.banner": "Essai gratuit: X jours restants",
    "trial.subscribe_now": "S'abonner maintenant",
    "tour.demo": "Vous visualisez une démonstration avec des données d'exemple. Les formulaires sont désactivés.",
    "tour.exit": "Quitter la démo et s'abonner",
  },
  de: {
    "common.back": "Zurück",
    
    "auth.login": "Anmelden",
    "auth.signup": "Registrieren",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.create_account": "Konto erstellen",
    "auth.forgot_password": "Passwort vergessen?",
    "auth.view_pricing": "Preise und Pläne anzeigen",
    
    "nav.dashboard": "Dashboard",
    "nav.new_invoice": "Neue Rechnung",
    "nav.invoices": "Rechnungen",
    "nav.quotes": "Angebote",
    "nav.clients": "Kunden",
    "nav.payments": "Zahlungen",
    "nav.inventory": "Inventar",
    "nav.photos": "Fotos",
    "nav.calculator": "Kostenkalkulator",
    "nav.settings": "Einstellungen",
    "nav.referrals": "Empfehlungen",
    
    "dashboard.new_invoice": "Neue Rechnung",
    "dashboard.create_invoice": "Erstelle eine neue Rechnung mit Fotos und Kostenhilfe.",
    "dashboard.quotes": "Angebote",
    "dashboard.quotes_desc": "Jobangebotstwürfe erstellen und verfolgen.",
    "dashboard.clients": "Kunden",
    "dashboard.clients_desc": "Speichern Sie Kunden einmalig, verwenden Sie sie immer wieder.",
    "dashboard.photos": "Fotos",
    "dashboard.photos_desc": "Durchsuchen Sie Jobfotos nach Rechnung.",
    "dashboard.invoices": "Rechnungen",
    "dashboard.invoices_desc": "Frühere Rechnungen anzeigen und verwalten.",
    "dashboard.payments": "Zahlungen",
    "dashboard.payments_desc": "Akzeptieren Sie Zahlungen und verfolgen Sie den Status.",
    "dashboard.inventory": "Inventar",
    "dashboard.inventory_desc": "Verfolgen Sie Vorräte, Materialien und Bestände.",
    "dashboard.calculator": "Kalkulator",
    "dashboard.calculator_desc": "Materialien, Stunden, Aufschlag – erledigt.",
    "dashboard.settings": "Einstellungen",
    "dashboard.settings_desc": "Logo, Geschäftsinfo, Standards.",
    "dashboard.referrals": "Empfehlungen",
    "dashboard.referrals_desc": "Teilen Sie Ihren Link, verdienen Sie 20% auf Lebenszeit.",
    
    "invoice.invoice": "RECHNUNG",
    "invoice.quote": "ANGEBOT",
    "invoice.invoice_number": "Rechnung #",
    "invoice.quote_number": "Angebot #",
    "invoice.date": "Datum",
    "invoice.due_date": "Fälligkeitsdatum",
    "invoice.client": "Rechnungsempfänger",
    "invoice.description": "Beschreibung",
    "invoice.quantity": "Menge",
    "invoice.unit_price": "Stückpreis",
    "invoice.total": "Gesamt",
    "invoice.subtotal": "Zwischensumme",
    "invoice.tax": "Steuern",
    "invoice.amount_due": "Fälliger Betrag",
    "invoice.notes": "Notizen",
    "invoice.thank_you": "Vielen Dank für Ihr Geschäft!",
    "invoice.download": "Herunterladen",
    "invoice.send": "Senden",
    
    "client.clients": "Kunden",
    "client.add": "Kunde hinzufügen",
    "client.name_placeholder": "Kundenname",
    "client.phone_placeholder": "Telefon",
    "client.email_placeholder": "E-Mail",
    "client.address_placeholder": "Adresse",
    
    "settings.title": "Einstellungen und Geschäftsinformationen",
    "settings.settings": "Einstellungen und Geschäftsinformationen",
    "settings.business_name": "Geschäftsname",
    "settings.phone": "Telefon",
    "settings.email": "E-Mail",
    "settings.address": "Adresse",
    "settings.website": "Webseite",
    "settings.default_tax": "Standard-Steuersatz %",
    "settings.default_markup": "Standard-Aufschlag %",
    "settings.footer": "Rechnungsfußzeilentext",
    "settings.invoice_footer": "Rechnungsfußzeilentext",
    "settings.logo": "Logo hochladen",
    "settings.upload_logo": "Logo hochladen",
    "settings.save": "Einstellungen speichern",
    "settings.language": "Sprache",
    "settings.invoice_template": "Rechnungsvorlage",
    "settings.saved": "Einstellungen gespeichert.",
    
    "template.choose_template": "Rechnungsvorlage Wählen",
    "template.choose_desc": "Klicken Sie auf eine Vorlage, um Ihre Rechnung in diesem Stil herunterzuladen.",
    
    "inventory.inventory": "Bestandsverwaltung",
    "inventory.add_item": "Artikel hinzufügen",
    "inventory.item_name": "Artikelname",
    "inventory.description": "Beschreibung",
    "inventory.category": "Kategorie",
    "inventory.quantity": "Menge",
    "inventory.unit_type": "Einheitstyp",
    "inventory.unit_price": "Stückpreis ($)",
    "inventory.low_stock": "Niedrigbestandsschwelle",
    "inventory.total_value": "Gesamtbestandswert",
    "inventory.items_in_stock": "Artikel im Bestand",
    "inventory.save_item": "Artikel speichern",
    "inventory.delete": "Löschen",
    "inventory.no_items": "Noch keine Bestandsartikel",
    "inventory.add_first": "Fügen Sie Ihren ersten Artikel hinzu",
    
    "payments.payment_collection": "Zahlungseinzug",
    "payments.stripe_status": "Stripe Connect Status",
    "payments.active": "Aktiv",
    "payments.not_enabled": "Nicht aktiviert",
    "payments.stats": "Zahlungsstatistiken",
    "payments.outstanding": "Ausstehend",
    "payments.paid_month": "Bezahlt (diesen Monat)",
    "payments.pending": "Ausstehend",
    "payments.how_it_works": "Wie es funktioniert",
    
    "referrals.referrals": "Empfehlungen – 20% auf Lebenszeit",
    "referrals.share": "Teilen Sie Ihren Link. Verdienen Sie 20% jeder monatlichen Zahlung aller, die Sie einbringen, solange sie abonniert bleiben.",
    "referrals.link": "Ihr Empfehlungslink",
    "referrals.copy": "Kopieren",
    "referrals.active": "Aktive Empfehlungen",
    "referrals.month": "Dieser Monat",
    "referrals.lifetime": "Lebenszeitgewinne",
    
    "trial.banner": "Kostenlos testen: X Tage verbleibend",
    "trial.subscribe_now": "Jetzt abonnieren",
    "tour.demo": "Sie sehen eine Demo mit Beispieldaten. Formulare sind deaktiviert.",
    "tour.exit": "Demo beenden und abonnieren",
  },
  pt: {
    "common.back": "Voltar",
    
    "auth.login": "Entrar",
    "auth.signup": "Registrar",
    "auth.email": "Email",
    "auth.password": "Senha",
    "auth.create_account": "Criar Conta",
    "auth.forgot_password": "Esqueceu a senha?",
    "auth.view_pricing": "Ver Preços e Planos",
    
    "nav.dashboard": "Painel",
    "nav.new_invoice": "Nova Fatura",
    "nav.invoices": "Faturas",
    "nav.quotes": "Orçamentos",
    "nav.clients": "Clientes",
    "nav.payments": "Pagamentos",
    "nav.inventory": "Inventário",
    "nav.photos": "Fotos",
    "nav.calculator": "Calculadora de Custos",
    "nav.settings": "Configurações",
    "nav.referrals": "Indicações",
    
    "dashboard.new_invoice": "Nova Fatura",
    "dashboard.create_invoice": "Crie uma nova fatura com fotos e ajuda de custos.",
    "dashboard.quotes": "Orçamentos",
    "dashboard.quotes_desc": "Rascunhe e acompanhe orçamentos de trabalhos.",
    "dashboard.clients": "Clientes",
    "dashboard.clients_desc": "Salve clientes uma vez, reutilize sempre.",
    "dashboard.photos": "Fotos",
    "dashboard.photos_desc": "Navegue em fotos de trabalhos por fatura.",
    "dashboard.invoices": "Faturas",
    "dashboard.invoices_desc": "Visualize e gerencie faturas anteriores.",
    "dashboard.payments": "Pagamentos",
    "dashboard.payments_desc": "Aceite pagamentos e acompanhe o status.",
    "dashboard.inventory": "Inventário",
    "dashboard.inventory_desc": "Acompanhe suprimentos, materiais e estoque.",
    "dashboard.calculator": "Calculadora",
    "dashboard.calculator_desc": "Materiais, horas, margem – pronto.",
    "dashboard.settings": "Configurações",
    "dashboard.settings_desc": "Logotipo, info empresarial, padrões.",
    "dashboard.referrals": "Indicações",
    "dashboard.referrals_desc": "Compartilhe seu link, ganhe 20% vitalício.",
    
    "invoice.invoice": "FATURA",
    "invoice.quote": "ORÇAMENTO",
    "invoice.invoice_number": "Fatura #",
    "invoice.quote_number": "Orçamento #",
    "invoice.date": "Data",
    "invoice.due_date": "Data de Vencimento",
    "invoice.client": "Faturar Para",
    "invoice.description": "Descrição",
    "invoice.quantity": "Qtd",
    "invoice.unit_price": "Preço Unitário",
    "invoice.total": "Total",
    "invoice.subtotal": "Subtotal",
    "invoice.tax": "Imposto",
    "invoice.amount_due": "Valor Devido",
    "invoice.notes": "Notas",
    "invoice.thank_you": "Obrigado pelo seu negócio!",
    "invoice.download": "Baixar",
    "invoice.send": "Enviar",
    
    "client.clients": "Clientes",
    "client.add": "Adicionar cliente",
    "client.name_placeholder": "Nome do cliente",
    "client.phone_placeholder": "Telefone",
    "client.email_placeholder": "Email",
    "client.address_placeholder": "Endereço",
    
    "settings.title": "Configurações e Informações Comerciais",
    "settings.settings": "Configurações e Informações Comerciais",
    "settings.business_name": "Nome da Empresa",
    "settings.phone": "Telefone",
    "settings.email": "Email",
    "settings.address": "Endereço",
    "settings.website": "Site",
    "settings.default_tax": "Imposto Padrão %",
    "settings.default_markup": "Margem Padrão %",
    "settings.footer": "Texto de Rodapé da Fatura",
    "settings.invoice_footer": "Texto de Rodapé da Fatura",
    "settings.logo": "Carregar Logotipo",
    "settings.upload_logo": "Carregar Logotipo",
    "settings.save": "Salvar Configurações",
    "settings.language": "Idioma",
    "settings.invoice_template": "Modelo de Fatura",
    "settings.saved": "Configurações salvas.",
    
    "template.choose_template": "Escolher Modelo de Fatura",
    "template.choose_desc": "Clique em um modelo para baixar sua fatura nesse estilo.",
    
    "inventory.inventory": "Gerenciamento de Inventário",
    "inventory.add_item": "Adicionar Item",
    "inventory.item_name": "Nome do Item",
    "inventory.description": "Descrição",
    "inventory.category": "Categoria",
    "inventory.quantity": "Quantidade",
    "inventory.unit_type": "Tipo de Unidade",
    "inventory.unit_price": "Preço Unitário ($)",
    "inventory.low_stock": "Limiar de Estoque Baixo",
    "inventory.total_value": "Valor Total do Inventário",
    "inventory.items_in_stock": "itens em estoque",
    "inventory.save_item": "Salvar Item",
    "inventory.delete": "Deletar",
    "inventory.no_items": "Sem itens de inventário ainda",
    "inventory.add_first": "Adicione Seu Primeiro Item",
    
    "payments.payment_collection": "Cobrança de Pagamentos",
    "payments.stripe_status": "Status do Stripe Connect",
    "payments.active": "Ativo",
    "payments.not_enabled": "Não Ativado",
    "payments.stats": "Estatísticas de Pagamento",
    "payments.outstanding": "Pendente",
    "payments.paid_month": "Pago (Este Mês)",
    "payments.pending": "Aguardando",
    "payments.how_it_works": "Como Funciona",
    
    "referrals.referrals": "Indicações – 20% Por Vida",
    "referrals.share": "Compartilhe seu link. Ganhe 20% de cada pagamento mensal de todos que você trazer, enquanto permanecerem inscritos.",
    "referrals.link": "Seu link de indicação",
    "referrals.copy": "Copiar",
    "referrals.active": "Indicações ativas",
    "referrals.month": "Este mês",
    "referrals.lifetime": "Ganho vitalício",
    
    "trial.banner": "Teste gratuito: X dias restantes",
    "trial.subscribe_now": "Inscrever-se Agora",
    "tour.demo": "Você está visualizando uma demonstração com dados de amostra. Formulários são desabilitados.",
    "tour.exit": "Sair da Demo e Inscrever-se",
  }
};

let currentLanguage = localStorage.getItem('tradebase-language') || 'en';

function setLanguage(lang) {
  if (LANGUAGES[lang]) {
    currentLanguage = lang;
    localStorage.setItem('tradebase-language', lang);
    applyLanguage();
    return true;
  }
  return false;
}

function t(key) {
  return TRANSLATIONS[currentLanguage]?.[key] || TRANSLATIONS['en']?.[key] || key;
}

function applyLanguage() {
  // Update all elements with data-i18n attribute
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (el.tagName === 'INPUT' && el.type === 'submit') {
      el.value = t(key);
    } else if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
      el.placeholder = t(key);
    } else if (el.tagName === 'LABEL') {
      el.textContent = t(key);
    } else {
      el.textContent = t(key);
    }
  });
  
  // Update all elements with data-i18n-placeholder attribute
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    el.placeholder = t(key);
  });
}

// Apply language on load - ensure language is set from localStorage before translating
document.addEventListener('DOMContentLoaded', () => {
  setLanguage(currentLanguage); // This calls applyLanguage internally
});
