// Multi-language support for TradeBase
const LANGUAGES = {
  en: { name: "English", flag: "🇺🇸" },
  es: { name: "Español", flag: "🇪🇸" },
  fr: { name: "Français", flag: "🇫🇷" },
  de: { name: "Deutsch", flag: "🇩🇪" },
  pt: { name: "Português", flag: "🇵🇹" }
};

const TRANSLATIONS = {
  en: {
    // Common
    "common.back": "Back",
    "common.cancel": "Cancel",
    
    // Auth
    "auth.login": "Log In",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.create_account": "Create Account",
    "auth.forgot_password": "Forgot password?",
    "auth.view_pricing": "View Pricing & Plans",
    "auth.login_error": "Invalid email or password",
    "auth.signup_error": "Could not create account",
    
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.new_invoice": "New Invoice",
    "nav.invoices": "Invoices",
    "nav.quotes": "Quotes",
    "nav.clients": "Clients",
    "nav.payments": "Payments",
    "nav.inventory": "Inventory",
    "nav.photos": "Photos",
    "nav.calculator": "Cost Calculator",
    "nav.settings": "Settings",
    "nav.referrals": "Referrals",
    
    // Dashboard
    "dashboard.new_invoice": "New Invoice",
    "dashboard.create_invoice": "Create a new invoice with photos & cost helper.",
    "dashboard.invoiced_month": "Invoiced This Month",
    "dashboard.paid_month": "Paid This Month",
    "dashboard.outstanding": "Outstanding Balance",
    "dashboard.quotes": "Quotes",
    "dashboard.quotes_desc": "Draft and track job quotes.",
    "dashboard.clients": "Clients",
    "dashboard.clients_desc": "Save clients once, reuse forever.",
    "dashboard.photos": "Photos",
    "dashboard.photos_desc": "Browse job photos by invoice.",
    "dashboard.invoices": "Invoices",
    "dashboard.invoices_desc": "View and manage past invoices.",
    "dashboard.payments": "Payments",
    "dashboard.payments_desc": "Accept payments & track status.",
    "dashboard.inventory": "Inventory",
    "dashboard.inventory_desc": "Track supplies, materials & stock.",
    "dashboard.calculator": "Cost Calculator",
    "dashboard.calculator_desc": "Materials, hours, markup – done.",
    "dashboard.settings": "Settings",
    "dashboard.settings_desc": "Logo, business info, defaults.",
    "dashboard.referrals": "Referrals",
    "dashboard.referrals_desc": "Share your link, earn 20% for life.",
    
    // Invoice
    "invoice.invoice": "INVOICE",
    "invoice.quote": "QUOTE",
    "invoice.invoice_number": "Invoice #",
    "invoice.quote_number": "Quote #",
    "invoice.date": "Date",
    "invoice.due_date": "Due Date",
    "invoice.client": "Bill To",
    "invoice.description": "Description",
    "invoice.quantity": "Qty",
    "invoice.unit_price": "Unit Price",
    "invoice.total": "Total",
    "invoice.subtotal": "Subtotal",
    "invoice.tax": "Tax",
    "invoice.amount_due": "Amount Due",
    "invoice.notes": "Notes",
    "invoice.payment_terms": "Payment Terms",
    "invoice.thank_you": "Thank you for your business!",
    "invoice.download": "Download",
    "invoice.send": "Send",
    "invoice.send_email": "Send Email",
    "invoice.email_modal_title": "Send Invoice via Email",
    "invoice.recipient_email": "Recipient Email",
    "invoice.recipient_name": "Recipient Name",
    "invoice.send_button": "Send Invoice",
    "invoice.no_client_email": "No client email saved - enter email address",
    "invoice.email_sent_success": "Invoice sent successfully!",
    "invoice.email_sent_error": "Failed to send invoice email",
    "invoice.email_required": "Email address is required",
    "invoice.email_invalid": "Veuillez entrer une adresse e-mail valide",
    "invoice.line_items": "Articles",
    "invoice.add_item": "+ Ajouter un article",
    "invoice.cost_helper": "Aide aux coûts et marge (facultatif)",
    "invoice.materials": "Coût du matériel",
    "invoice.labor_hours": "Heures de travail",
    "invoice.hourly_rate": "Tarif horaire",
    "invoice.markup": "Marge %",
    "invoice.client_placeholder": "Tapez le nom du client ou sélectionnez un client enregistré",
    "invoice.notes_placeholder": "Notes facultatives pour le client",
    "invoice.save_client": "Save as new client",
    "invoice.invoices": "Invoices",
    "invoice.photos": "Photos",
    "invoice.calculate": "Calculate",
    "invoice.tax_label": "Tax",
    "invoice.save": "Save Invoice",
    "invoice.new_invoice": "New Invoice",
    
    // Quotes
    "quote.quotes": "Quotes",
    "quote.new_quote": "+ New Quote",
    "quote.client_placeholder": "Type client name or select saved client",
    "quote.notes_placeholder": "Optional notes for the client",
    "quote.date": "Date",
    "quote.line_items": "Line Items",
    "quote.add_item": "+ Add Item",
    "quote.subtotal": "Subtotal",
    "quote.tax": "Tax",
    "quote.total": "Total",
    "quote.save": "Save Quote",
    
    // Clients
    "client.clients": "Clients",
    "client.add": "Add Client",
    "client.name_placeholder": "Client name",
    "client.phone_placeholder": "Phone",
    "client.email_placeholder": "Email",
    "client.address_placeholder": "Address",
    
    // Settings
    "settings.title": "Settings & Business Info",
    "settings.settings": "Settings & Business Info",
    "settings.business_name": "Business Name",
    "settings.phone": "Phone",
    "settings.email": "Email",
    "settings.address": "Address",
    "settings.website": "Website",
    "settings.default_tax": "Default Tax %",
    "settings.default_markup": "Default Markup %",
    "settings.footer": "Invoice Footer Text",
    "settings.invoice_footer": "Invoice Footer Text",
    "settings.logo": "Upload Logo",
    "settings.upload_logo": "Upload Logo",
    "settings.save": "Save Settings",
    "settings.language": "Language",
    "settings.invoice_template": "Invoice Template",
    "settings.saved": "Settings saved.",
    
    // Template Chooser
    "template.choose_template": "Choose Invoice Template",
    "template.choose_desc": "Click a template to download your invoice in that style.",
    
    // Inventory
    "inventory.title": "Inventory",
    "inventory.inventory": "Inventory Management",
    "inventory.add_item": "Add Item",
    "inventory.item_name": "Item Name",
    "inventory.description": "Description",
    "inventory.category": "Category",
    "inventory.quantity": "Quantity",
    "inventory.unit_type": "Unit Type",
    "inventory.unit_price": "Unit Price ($)",
    "inventory.low_stock": "Low Stock Threshold",
    "inventory.total_value": "Total Inventory Value",
    "inventory.items_in_stock": "items in stock",
    "inventory.save_item": "Save Item",
    "inventory.delete": "Delete",
    "inventory.no_items": "No inventory items yet",
    "inventory.add_first": "Add Your First Item",
    
    // Payments
    "payments.title": "Payments",
    "payments.payment_collection": "Payment Collection",
    "payments.stripe_status": "Stripe Connect Status",
    "payments.active": "Active",
    "payments.not_enabled": "Not Enabled",
    "payments.connect_message": "Connect your Stripe account to start collecting payments from invoices.",
    "payments.enable_button": "Enable Payment Collection",
    "payments.enabling": "Enabling...",
    "payments.enabled_message": "Payment collection is enabled. You can generate payment links for your invoices.",
    "payments.stats": "Payment Statistics",
    "payments.outstanding": "Outstanding",
    "payments.paid_month": "Paid (This Month)",
    "payments.pending": "Pending",
    "payments.how_it_works": "How It Works",
    
    // Referrals
    "referrals.referrals": "Referrals – 20% For Life",
    "referrals.share": "Share your link. Earn 20% of every monthly payment for everyone you bring in, for as long as they stay subscribed.",
    "referrals.link": "Your referral link",
    "referrals.copy": "Copy",
    "referrals.active": "Active referrals",
    "referrals.month": "This month",
    "referrals.lifetime": "Lifetime earned",
    
    // Pricing
    "pricing.choose_plan": "Choose Your Plan",
    "pricing.monthly": "Monthly",
    "pricing.yearly": "Yearly",
    "pricing.lifetime_early": "Lifetime Early Bird",
    "pricing.lifetime_regular": "Lifetime Regular",
    "pricing.per_month": "/month",
    "pricing.per_year": "/year",
    "pricing.one_time": "one-time",
    "pricing.trial_included": "7-day free trial included!",
    "pricing.yearly_savings": "Save $20/year · 2 months free!",
    "pricing.monthly_desc": "Get started free for 7 days",
    "pricing.yearly_desc": "Best value - save 2 months",
    "pricing.first_500": "First 500 only",
    "pricing.spots_left": "spots left",
    "pricing.after_early": "After early bird spots filled",
    "pricing.best_value": "BEST VALUE",
    "pricing.limited_offer": "LIMITED OFFER",
    "pricing.start_trial": "Start Free Trial",
    "pricing.subscribe_now": "Subscribe Now",
    "pricing.get_lifetime": "Get Lifetime Access",
    "pricing.feature_unlimited_invoices": "Unlimited invoices",
    "pricing.feature_unlimited_quotes": "Unlimited quotes",
    "pricing.feature_client_mgmt": "Client management",
    "pricing.feature_photos": "Photo attachments",
    "pricing.feature_branding": "Business logo & branding",
    "pricing.feature_calculator": "Cost calculator",
    "pricing.feature_download": "Invoice download (PNG)",
    "pricing.feature_email_invoices": "Email invoices to clients",
    "pricing.feature_quote_convert": "Convert quotes to invoices",
    "pricing.feature_dashboard": "Monthly financial dashboard",
    "pricing.feature_stripe": "Stripe payment collection",
    "pricing.feature_inventory": "Inventory management",
    "pricing.feature_all_forever": "All features forever",
    "pricing.feature_no_fees": "No monthly fees",
    "pricing.feature_priority": "Priority support",
    "pricing.feature_updates": "Lifetime updates",
    "pricing.feature_early_access": "Early access to new features",
    "pricing.feature_payment_included": "Payment collection included",
    "pricing.referral_title": "Earn 20% Commission",
    "pricing.referral_desc": "Refer friends and colleagues to TradeBase and earn 20% recurring commission on their subscription. The more you share, the more you earn!",
    "pricing.referral_note": "Get your referral link after subscribing",
    "pricing.take_tour": "Take a Tour",
    "pricing.tour_desc": "See all features in action with sample data",
    
    // Trial & Auth
    "trial.banner": "Free trial: X days remaining",
    "trial.subscribe_now": "Subscribe Now",
    "tour.demo": "You're viewing a demo with sample data. Forms are disabled.",
    "tour.exit": "Exit Tour & Subscribe",
    "tour.email_disabled": "Email sending is disabled in tour mode",
    "tour.convert_disabled": "Converting quotes is disabled in tour mode",
    
    // Quote
    "quote.convert_to_invoice": "Convert to Invoice",
    "quote.converted_success": "Quote converted to invoice. Fill in any additional details and save.",
  },
  es: {
    "common.back": "Atrás",
    "common.cancel": "Cancelar",
    
    "auth.login": "Iniciar sesión",
    "auth.signup": "Registrarse",
    "auth.email": "Correo",
    "auth.password": "Contraseña",
    "auth.create_account": "Crear cuenta",
    "auth.forgot_password": "¿Olvidaste la contraseña?",
    "auth.view_pricing": "Ver precios y planes",
    
    "nav.dashboard": "Panel",
    "nav.new_invoice": "Nueva factura",
    "nav.invoices": "Facturas",
    "nav.quotes": "Presupuestos",
    "nav.clients": "Clientes",
    "nav.payments": "Pagos",
    "nav.inventory": "Inventario",
    "nav.photos": "Fotos",
    "nav.calculator": "Calculadora de costos",
    "nav.settings": "Configuración",
    "nav.referrals": "Referidos",
    
    "dashboard.new_invoice": "Nueva factura",
    "dashboard.create_invoice": "Crea una nueva factura con fotos y ayuda de costos.",
    "dashboard.invoiced_month": "Facturado este mes",
    "dashboard.paid_month": "Pagado este mes",
    "dashboard.outstanding": "Saldo pendiente",
    "dashboard.quotes": "Presupuestos",
    "dashboard.quotes_desc": "Redacta y realiza un seguimiento de presupuestos de trabajos.",
    "dashboard.clients": "Clientes",
    "dashboard.clients_desc": "Guarda clientes una vez, reutiliza siempre.",
    "dashboard.photos": "Fotos",
    "dashboard.photos_desc": "Examina fotos de trabajo por factura.",
    "dashboard.invoices": "Facturas",
    "dashboard.invoices_desc": "Ver y gestionar facturas anteriores.",
    "dashboard.payments": "Pagos",
    "dashboard.payments_desc": "Acepta pagos y realiza un seguimiento del estado.",
    "dashboard.inventory": "Inventario",
    "dashboard.inventory_desc": "Realiza un seguimiento de suministros, materiales y existencias.",
    "dashboard.calculator": "Calculadora",
    "dashboard.calculator_desc": "Materiales, horas, margen – hecho.",
    "dashboard.settings": "Configuración",
    "dashboard.settings_desc": "Logotipo, info empresarial, predeterminados.",
    "dashboard.referrals": "Referidos",
    "dashboard.referrals_desc": "Comparte tu enlace, gana 20% de por vida.",
    
    "invoice.invoice": "FACTURA",
    "invoice.quote": "PRESUPUESTO",
    "invoice.invoice_number": "Factura #",
    "invoice.quote_number": "Presupuesto #",
    "invoice.date": "Fecha",
    "invoice.due_date": "Fecha de vencimiento",
    "invoice.client": "Facturar a",
    "invoice.description": "Descripción",
    "invoice.quantity": "Cantidad",
    "invoice.unit_price": "Precio unitario",
    "invoice.total": "Total",
    "invoice.subtotal": "Subtotal",
    "invoice.tax": "Impuesto",
    "invoice.amount_due": "Cantidad debida",
    "invoice.notes": "Notas",
    "invoice.thank_you": "¡Gracias por tu negocio!",
    "invoice.download": "Descargar",
    "invoice.send": "Enviar",
    "invoice.send_email": "Enviar correo",
    "invoice.email_modal_title": "Enviar factura por correo",
    "invoice.recipient_email": "Correo del destinatario",
    "invoice.recipient_name": "Nombre del destinatario",
    "invoice.send_button": "Enviar factura",
    "invoice.no_client_email": "No hay correo del cliente guardado - ingrese dirección de correo",
    "invoice.email_sent_success": "¡Factura enviada con éxito!",
    "invoice.email_sent_error": "Error al enviar el correo de la factura",
    "invoice.email_required": "Se requiere dirección de correo electrónico",
    "invoice.email_invalid": "Por favor ingrese una dirección de correo electrónico válida",
    "invoice.client_placeholder": "Escriba el nombre del cliente o seleccione un cliente guardado",
    "invoice.notes_placeholder": "Notas opcionales para el cliente",
    "invoice.save_client": "Guardar como nuevo cliente",
    "invoice.invoices": "Facturas",
    "invoice.photos": "Fotos",
    "invoice.calculate": "Calcular",
    "invoice.tax_label": "Impuesto",
    "invoice.save": "Guardar factura",
    "invoice.new_invoice": "Nueva factura",
    
    "quote.quotes": "Presupuestos",
    "quote.new_quote": "+ Nuevo Presupuesto",
    "quote.client_placeholder": "Escriba el nombre del cliente o seleccione un cliente guardado",
    "quote.notes_placeholder": "Notas opcionales para el cliente",
    "quote.date": "Fecha",
    "quote.line_items": "Artículos",
    "quote.add_item": "+ Agregar artículo",
    "quote.subtotal": "Subtotal",
    "quote.tax": "Impuesto",
    "quote.total": "Total",
    "quote.save": "Guardar presupuesto",
    
    "client.clients": "Clientes",
    "client.add": "Agregar cliente",
    "client.name_placeholder": "Nombre del cliente",
    "client.phone_placeholder": "Teléfono",
    "client.email_placeholder": "Correo electrónico",
    "client.address_placeholder": "Dirección",
    
    "settings.title": "Configuración e información comercial",
    "settings.settings": "Configuración e información comercial",
    "settings.business_name": "Nombre del negocio",
    "settings.phone": "Teléfono",
    "settings.email": "Correo",
    "settings.address": "Dirección",
    "settings.website": "Sitio web",
    "settings.default_tax": "Impuesto predeterminado %",
    "settings.default_markup": "Margen predeterminado %",
    "settings.footer": "Texto de pie de factura",
    "settings.invoice_footer": "Texto de pie de factura",
    "settings.logo": "Cargar logo",
    "settings.upload_logo": "Cargar logo",
    "settings.save": "Guardar configuración",
    "settings.language": "Idioma",
    "settings.invoice_template": "Plantilla de factura",
    "settings.saved": "Configuración guardada.",
    
    "template.choose_template": "Elegir Plantilla de Factura",
    "template.choose_desc": "Haz clic en una plantilla para descargar tu factura en ese estilo.",
    
    "inventory.title": "Inventario",
    "inventory.inventory": "Gestión de inventario",
    "inventory.add_item": "Agregar artículo",
    "inventory.item_name": "Nombre del artículo",
    "inventory.description": "Descripción",
    "inventory.category": "Categoría",
    "inventory.quantity": "Cantidad",
    "inventory.unit_type": "Tipo de unidad",
    "inventory.unit_price": "Precio unitario ($)",
    "inventory.low_stock": "Umbral de bajo stock",
    "inventory.total_value": "Valor total del inventario",
    "inventory.items_in_stock": "artículos en stock",
    "inventory.save_item": "Guardar artículo",
    "inventory.delete": "Eliminar",
    "inventory.no_items": "Sin artículos de inventario aún",
    "inventory.add_first": "Agregar tu primer artículo",
    
    "payments.title": "Pagos",
    "payments.payment_collection": "Cobro de pagos",
    "payments.stripe_status": "Estado de Stripe Connect",
    "payments.active": "Activo",
    "payments.not_enabled": "No habilitado",
    "payments.connect_message": "Conecta tu cuenta de Stripe para comenzar a cobrar pagos de facturas.",
    "payments.enable_button": "Habilitar cobro de pagos",
    "payments.enabling": "Habilitando...",
    "payments.enabled_message": "El cobro de pagos está habilitado. Puedes generar enlaces de pago para tus facturas.",
    "payments.stats": "Estadísticas de pago",
    "payments.outstanding": "Pendiente",
    "payments.paid_month": "Pagado (este mes)",
    "payments.pending": "En espera",
    "payments.how_it_works": "Cómo funciona",
    
    "referrals.referrals": "Referidos – 20% de por vida",
    "referrals.share": "Comparte tu enlace. Gana el 20% de cada pago mensual de todos los que traigas, mientras permanezcan suscritos.",
    "referrals.link": "Tu enlace de referencia",
    "referrals.copy": "Copiar",
    "referrals.active": "Referidos activos",
    "referrals.month": "Este mes",
    "referrals.lifetime": "Ganancia de por vida",
    
    "pricing.choose_plan": "Elige tu plan",
    "pricing.monthly": "Mensual",
    "pricing.yearly": "Anual",
    "pricing.lifetime_early": "Vitalicio Preventa",
    "pricing.lifetime_regular": "Vitalicio Regular",
    "pricing.per_month": "/mes",
    "pricing.per_year": "/año",
    "pricing.one_time": "pago único",
    "pricing.trial_included": "¡Prueba gratuita de 7 días incluida!",
    "pricing.yearly_savings": "Ahorra $20/año · ¡2 meses gratis!",
    "pricing.monthly_desc": "Comienza gratis por 7 días",
    "pricing.yearly_desc": "Mejor valor - ahorra 2 meses",
    "pricing.first_500": "Solo los primeros 500",
    "pricing.spots_left": "espacios disponibles",
    "pricing.after_early": "Después de completar los espacios de preventa",
    "pricing.best_value": "MEJOR VALOR",
    "pricing.limited_offer": "OFERTA LIMITADA",
    "pricing.start_trial": "Comenzar prueba gratuita",
    "pricing.subscribe_now": "Suscribirse ahora",
    "pricing.get_lifetime": "Obtener acceso vitalicio",
    "pricing.feature_unlimited_invoices": "Facturas ilimitadas",
    "pricing.feature_unlimited_quotes": "Presupuestos ilimitados",
    "pricing.feature_client_mgmt": "Gestión de clientes",
    "pricing.feature_photos": "Fotos adjuntas",
    "pricing.feature_branding": "Logo y marca empresarial",
    "pricing.feature_calculator": "Calculadora de costos",
    "pricing.feature_download": "Descarga de facturas (PNG)",
    "pricing.feature_all_forever": "Todas las funciones para siempre",
    "pricing.feature_no_fees": "Sin tarifas mensuales",
    "pricing.feature_priority": "Soporte prioritario",
    "pricing.feature_updates": "Actualizaciones vitalicias",
    "pricing.feature_early_access": "Acceso anticipado a nuevas funciones",
    "pricing.feature_payment_included": "Cobro de pagos incluido",
    "pricing.addon_title": "Agregar cobro de pagos",
    "pricing.addon_notice": "Disponible solo para planes Mensual y Anual",
    "pricing.addon_stripe": "Integración Stripe Connect",
    "pricing.addon_desc": "Conecta tu cuenta de Stripe para cobrar pagos directamente de las facturas enviadas a tus clientes",
    "pricing.referral_title": "Gana 20% de comisión",
    "pricing.referral_desc": "Refiere amigos y colegas a TradeBase y gana 20% de comisión recurrente en su suscripción. ¡Cuanto más compartas, más ganarás!",
    "pricing.referral_note": "Obtén tu enlace de referido después de suscribirte",
    "pricing.take_tour": "Hacer un recorrido",
    "pricing.tour_desc": "Ver todas las funciones en acción con datos de ejemplo",
    
    "trial.banner": "Prueba gratuita: X días restantes",
    "trial.subscribe_now": "Suscribirse ahora",
    "tour.demo": "Estás viendo una demostración con datos de ejemplo. Los formularios están deshabilitados.",
    "tour.exit": "Salir de la demostración y suscribirse",
    "tour.email_disabled": "El envío de correo está deshabilitado en modo demo",
    "tour.convert_disabled": "La conversión de presupuestos está deshabilitada en modo demo",
    
    "quote.convert_to_invoice": "Convertir a factura",
    "quote.converted_success": "Presupuesto convertido a factura. Complete los detalles adicionales y guarde.",
  },
  fr: {
    "common.back": "Retour",
    "common.cancel": "Annuler",
    
    "auth.login": "Connexion",
    "auth.signup": "Inscription",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.create_account": "Créer un compte",
    "auth.forgot_password": "Mot de passe oublié?",
    "auth.view_pricing": "Voir les tarifs et plans",
    
    "nav.dashboard": "Tableau de bord",
    "nav.new_invoice": "Nouvelle facture",
    "nav.invoices": "Factures",
    "nav.quotes": "Devis",
    "nav.clients": "Clients",
    "nav.payments": "Paiements",
    "nav.inventory": "Inventaire",
    "nav.photos": "Photos",
    "nav.calculator": "Calculatrice de coûts",
    "nav.settings": "Paramètres",
    "nav.referrals": "Parrainages",
    
    "dashboard.new_invoice": "Nouvelle facture",
    "dashboard.create_invoice": "Créez une nouvelle facture avec photos et aide aux coûts.",
    "dashboard.invoiced_month": "Facturé ce mois",
    "dashboard.paid_month": "Payé ce mois",
    "dashboard.outstanding": "Solde impayé",
    "dashboard.quotes": "Devis",
    "dashboard.quotes_desc": "Rédigez et suivez les devis de travaux.",
    "dashboard.clients": "Clients",
    "dashboard.clients_desc": "Enregistrez les clients une fois, réutilisez toujours.",
    "dashboard.photos": "Photos",
    "dashboard.photos_desc": "Parcourez les photos de travaux par facture.",
    "dashboard.invoices": "Factures",
    "dashboard.invoices_desc": "Afficher et gérer les factures passées.",
    "dashboard.payments": "Paiements",
    "dashboard.payments_desc": "Acceptez les paiements et suivez le statut.",
    "dashboard.inventory": "Inventaire",
    "dashboard.inventory_desc": "Suivez les fournitures, matériaux et stock.",
    "dashboard.calculator": "Calculatrice",
    "dashboard.calculator_desc": "Matériaux, heures, marge – terminé.",
    "dashboard.settings": "Paramètres",
    "dashboard.settings_desc": "Logo, infos entreprise, défauts.",
    "dashboard.referrals": "Parrainages",
    "dashboard.referrals_desc": "Partagez votre lien, gagnez 20% à vie.",
    
    "invoice.invoice": "FACTURE",
    "invoice.quote": "DEVIS",
    "invoice.invoice_number": "Facture #",
    "invoice.quote_number": "Devis #",
    "invoice.date": "Date",
    "invoice.due_date": "Date d'échéance",
    "invoice.client": "Facturer à",
    "invoice.description": "Description",
    "invoice.quantity": "Qté",
    "invoice.unit_price": "Prix unitaire",
    "invoice.total": "Total",
    "invoice.subtotal": "Sous-total",
    "invoice.tax": "Taxe",
    "invoice.amount_due": "Montant dû",
    "invoice.notes": "Notes",
    "invoice.thank_you": "Merci pour votre confiance!",
    "invoice.download": "Télécharger",
    "invoice.send": "Envoyer",
    "invoice.send_email": "Envoyer email",
    "invoice.email_modal_title": "Envoyer la facture par email",
    "invoice.recipient_email": "Email du destinataire",
    "invoice.recipient_name": "Nom du destinataire",
    "invoice.send_button": "Envoyer la facture",
    "invoice.no_client_email": "Aucun email client enregistré - saisissez l'adresse email",
    "invoice.email_sent_success": "Facture envoyée avec succès!",
    "invoice.email_sent_error": "Échec de l'envoi de l'email de facture",
    "invoice.email_required": "L'adresse e-mail est requise",
    "invoice.email_invalid": "Veuillez saisir une adresse e-mail valide",
    "invoice.client_placeholder": "Tapez le nom du client ou sélectionnez un client enregistré",
    "invoice.notes_placeholder": "Notes facultatives pour le client",
    "invoice.save_client": "Enregistrer comme nouveau client",
    "invoice.invoices": "Factures",
    "invoice.photos": "Photos",
    "invoice.calculate": "Calculer",
    "invoice.tax_label": "Taxe",
    "invoice.save": "Enregistrer la facture",
    "invoice.new_invoice": "Nouvelle facture",
    
    "quote.quotes": "Devis",
    "quote.new_quote": "+ Nouveau Devis",
    "quote.client_placeholder": "Tapez le nom du client ou sélectionnez un client enregistré",
    "quote.notes_placeholder": "Notes facultatives pour le client",
    "quote.date": "Date",
    "quote.line_items": "Articles",
    "quote.add_item": "+ Ajouter un article",
    "quote.subtotal": "Sous-total",
    "quote.tax": "Taxe",
    "quote.total": "Total",
    "quote.save": "Enregistrer le devis",
    
    "client.clients": "Clients",
    "client.add": "Ajouter un client",
    "client.name_placeholder": "Nom du client",
    "client.phone_placeholder": "Téléphone",
    "client.email_placeholder": "Email",
    "client.address_placeholder": "Adresse",
    
    "settings.title": "Paramètres et informations commerciales",
    "settings.settings": "Paramètres et informations commerciales",
    "settings.business_name": "Nom de l'entreprise",
    "settings.phone": "Téléphone",
    "settings.email": "Email",
    "settings.address": "Adresse",
    "settings.website": "Site web",
    "settings.default_tax": "Taxe par défaut %",
    "settings.default_markup": "Marge par défaut %",
    "settings.footer": "Texte de pied de page de facture",
    "settings.invoice_footer": "Texte de pied de page de facture",
    "settings.logo": "Charger le logo",
    "settings.upload_logo": "Charger le logo",
    "settings.save": "Enregistrer les paramètres",
    "settings.language": "Langue",
    "settings.invoice_template": "Modèle de facture",
    "settings.saved": "Paramètres enregistrés.",
    
    "template.choose_template": "Choisir un Modèle de Facture",
    "template.choose_desc": "Cliquez sur un modèle pour télécharger votre facture dans ce style.",
    
    "inventory.title": "Inventaire",
    "inventory.inventory": "Gestion de l'inventaire",
    "inventory.add_item": "Ajouter un article",
    "inventory.item_name": "Nom de l'article",
    "inventory.description": "Description",
    "inventory.category": "Catégorie",
    "inventory.quantity": "Quantité",
    "inventory.unit_type": "Type d'unité",
    "inventory.unit_price": "Prix unitaire ($)",
    "inventory.low_stock": "Seuil de stock faible",
    "inventory.total_value": "Valeur totale de l'inventaire",
    "inventory.items_in_stock": "articles en stock",
    "inventory.save_item": "Enregistrer l'article",
    "inventory.delete": "Supprimer",
    "inventory.no_items": "Pas encore d'articles d'inventaire",
    "inventory.add_first": "Ajouter votre premier article",
    
    "payments.title": "Paiements",
    "payments.payment_collection": "Recouvrement des paiements",
    "payments.stripe_status": "Statut de Stripe Connect",
    "payments.active": "Actif",
    "payments.not_enabled": "Non activé",
    "payments.connect_message": "Connectez votre compte Stripe pour commencer à collecter les paiements des factures.",
    "payments.enable_button": "Activer la collecte de paiements",
    "payments.enabling": "Activation...",
    "payments.enabled_message": "La collecte de paiements est activée. Vous pouvez générer des liens de paiement pour vos factures.",
    "payments.stats": "Statistiques de paiement",
    "payments.outstanding": "Impayé",
    "payments.paid_month": "Payé (ce mois)",
    "payments.pending": "En attente",
    "payments.how_it_works": "Comment ça marche",
    
    "referrals.referrals": "Parrainages – 20% à vie",
    "referrals.share": "Partagez votre lien. Gagnez 20% de chaque paiement mensuel de tous ceux que vous apportez, tant qu'ils restent abonnés.",
    "referrals.link": "Votre lien de parrainage",
    "referrals.copy": "Copier",
    "referrals.active": "Parrainages actifs",
    "referrals.month": "Ce mois",
    "referrals.lifetime": "Gains à vie",
    
    "pricing.choose_plan": "Choisissez votre plan",
    "pricing.monthly": "Mensuel",
    "pricing.yearly": "Annuel",
    "pricing.lifetime_early": "Vie Early Bird",
    "pricing.lifetime_regular": "Vie Régulier",
    "pricing.per_month": "/mois",
    "pricing.per_year": "/an",
    "pricing.one_time": "paiement unique",
    "pricing.trial_included": "Essai gratuit de 7 jours inclus!",
    "pricing.yearly_savings": "Économisez 20$/an · 2 mois gratuits!",
    "pricing.monthly_desc": "Commencez gratuitement pendant 7 jours",
    "pricing.yearly_desc": "Meilleure valeur - économisez 2 mois",
    "pricing.first_500": "Seulement les 500 premiers",
    "pricing.spots_left": "places restantes",
    "pricing.after_early": "Après les places early bird",
    "pricing.best_value": "MEILLEURE VALEUR",
    "pricing.limited_offer": "OFFRE LIMITÉE",
    "pricing.start_trial": "Commencer l'essai gratuit",
    "pricing.subscribe_now": "S'abonner maintenant",
    "pricing.get_lifetime": "Obtenir un accès à vie",
    "pricing.feature_unlimited_invoices": "Factures illimitées",
    "pricing.feature_unlimited_quotes": "Devis illimités",
    "pricing.feature_client_mgmt": "Gestion des clients",
    "pricing.feature_photos": "Photos jointes",
    "pricing.feature_branding": "Logo et image de marque",
    "pricing.feature_calculator": "Calculatrice de coûts",
    "pricing.feature_download": "Téléchargement de facture (PNG)",
    "pricing.feature_all_forever": "Toutes les fonctionnalités pour toujours",
    "pricing.feature_no_fees": "Pas de frais mensuels",
    "pricing.feature_priority": "Support prioritaire",
    "pricing.feature_updates": "Mises à jour à vie",
    "pricing.feature_early_access": "Accès anticipé aux nouvelles fonctionnalités",
    "pricing.feature_payment_included": "Collecte de paiements incluse",
    "pricing.addon_title": "Ajouter la collecte de paiements",
    "pricing.addon_notice": "Disponible uniquement pour les forfaits Mensuel et Annuel",
    "pricing.addon_stripe": "Intégration Stripe Connect",
    "pricing.addon_desc": "Connectez votre compte Stripe pour collecter les paiements directement à partir des factures envoyées à vos clients",
    "pricing.referral_title": "Gagnez 20% de commission",
    "pricing.referral_desc": "Parrainez des amis et collègues à TradeBase et gagnez 20% de commission récurrente sur leur abonnement. Plus vous partagez, plus vous gagnez!",
    "pricing.referral_note": "Obtenez votre lien de parrainage après vous être abonné",
    "pricing.take_tour": "Faire un tour",
    "pricing.tour_desc": "Voir toutes les fonctionnalités en action avec des données d'exemple",
    
    "trial.banner": "Essai gratuit: X jours restants",
    "trial.subscribe_now": "S'abonner maintenant",
    "tour.demo": "Vous visualisez une démonstration avec des données d'exemple. Les formulaires sont désactivés.",
    "tour.exit": "Quitter la démo et s'abonner",
    "tour.email_disabled": "L'envoi d'email est désactivé en mode démo",
    "tour.convert_disabled": "La conversion de devis est désactivée en mode démo",
    
    "quote.convert_to_invoice": "Convertir en facture",
    "quote.converted_success": "Devis converti en facture. Remplissez les détails supplémentaires et enregistrez.",
  },
  de: {
    "common.back": "Zurück",
    "common.cancel": "Abbrechen",
    
    "auth.login": "Anmelden",
    "auth.signup": "Registrieren",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.create_account": "Konto erstellen",
    "auth.forgot_password": "Passwort vergessen?",
    "auth.view_pricing": "Preise und Pläne anzeigen",
    
    "nav.dashboard": "Dashboard",
    "nav.new_invoice": "Neue Rechnung",
    "nav.invoices": "Rechnungen",
    "nav.quotes": "Angebote",
    "nav.clients": "Kunden",
    "nav.payments": "Zahlungen",
    "nav.inventory": "Inventar",
    "nav.photos": "Fotos",
    "nav.calculator": "Kostenkalkulator",
    "nav.settings": "Einstellungen",
    "nav.referrals": "Empfehlungen",
    
    "dashboard.new_invoice": "Neue Rechnung",
    "dashboard.create_invoice": "Erstelle eine neue Rechnung mit Fotos und Kostenhilfe.",
    "dashboard.invoiced_month": "Diesen Monat in Rechnung gestellt",
    "dashboard.paid_month": "Diesen Monat bezahlt",
    "dashboard.outstanding": "Ausstehender Betrag",
    "dashboard.quotes": "Angebote",
    "dashboard.quotes_desc": "Jobangebotstwürfe erstellen und verfolgen.",
    "dashboard.clients": "Kunden",
    "dashboard.clients_desc": "Speichern Sie Kunden einmalig, verwenden Sie sie immer wieder.",
    "dashboard.photos": "Fotos",
    "dashboard.photos_desc": "Durchsuchen Sie Jobfotos nach Rechnung.",
    "dashboard.invoices": "Rechnungen",
    "dashboard.invoices_desc": "Frühere Rechnungen anzeigen und verwalten.",
    "dashboard.payments": "Zahlungen",
    "dashboard.payments_desc": "Akzeptieren Sie Zahlungen und verfolgen Sie den Status.",
    "dashboard.inventory": "Inventar",
    "dashboard.inventory_desc": "Verfolgen Sie Vorräte, Materialien und Bestände.",
    "dashboard.calculator": "Kalkulator",
    "dashboard.calculator_desc": "Materialien, Stunden, Aufschlag – erledigt.",
    "dashboard.settings": "Einstellungen",
    "dashboard.settings_desc": "Logo, Geschäftsinfo, Standards.",
    "dashboard.referrals": "Empfehlungen",
    "dashboard.referrals_desc": "Teilen Sie Ihren Link, verdienen Sie 20% auf Lebenszeit.",
    
    "invoice.invoice": "RECHNUNG",
    "invoice.quote": "ANGEBOT",
    "invoice.invoice_number": "Rechnung #",
    "invoice.quote_number": "Angebot #",
    "invoice.date": "Datum",
    "invoice.due_date": "Fälligkeitsdatum",
    "invoice.client": "Rechnungsempfänger",
    "invoice.description": "Beschreibung",
    "invoice.quantity": "Menge",
    "invoice.unit_price": "Stückpreis",
    "invoice.total": "Gesamt",
    "invoice.subtotal": "Zwischensumme",
    "invoice.tax": "Steuern",
    "invoice.amount_due": "Fälliger Betrag",
    "invoice.notes": "Notizen",
    "invoice.thank_you": "Vielen Dank für Ihr Geschäft!",
    "invoice.download": "Herunterladen",
    "invoice.send": "Senden",
    "invoice.send_email": "E-Mail senden",
    "invoice.email_modal_title": "Rechnung per E-Mail senden",
    "invoice.recipient_email": "Empfänger-E-Mail",
    "invoice.recipient_name": "Empfängername",
    "invoice.send_button": "Rechnung senden",
    "invoice.no_client_email": "Keine Kunden-E-Mail gespeichert - E-Mail-Adresse eingeben",
    "invoice.email_sent_success": "Rechnung erfolgreich gesendet!",
    "invoice.email_sent_error": "Fehler beim Senden der Rechnungs-E-Mail",
    "invoice.email_required": "E-Mail-Adresse ist erforderlich",
    "invoice.email_invalid": "Bitte geben Sie eine gültige E-Mail-Adresse ein",
    "invoice.client_placeholder": "Geben Sie den Kundennamen ein oder wählen Sie einen gespeicherten Kunden",
    "invoice.notes_placeholder": "Optionale Notizen für den Kunden",
    "invoice.save_client": "Als neuen Kunden speichern",
    "invoice.invoices": "Rechnungen",
    "invoice.photos": "Fotos",
    "invoice.calculate": "Berechnen",
    "invoice.tax_label": "Steuer",
    "invoice.save": "Rechnung speichern",
    "invoice.new_invoice": "Neue Rechnung",
    
    "quote.quotes": "Angebote",
    "quote.new_quote": "+ Neues Angebot",
    "quote.client_placeholder": "Geben Sie den Kundennamen ein oder wählen Sie einen gespeicherten Kunden",
    "quote.notes_placeholder": "Optionale Notizen für den Kunden",
    "quote.date": "Datum",
    "quote.line_items": "Einzelposten",
    "quote.add_item": "+ Artikel hinzufügen",
    "quote.subtotal": "Zwischensumme",
    "quote.tax": "Steuern",
    "quote.total": "Gesamt",
    "quote.save": "Angebot speichern",
    
    "client.clients": "Kunden",
    "client.add": "Kunde hinzufügen",
    "client.name_placeholder": "Kundenname",
    "client.phone_placeholder": "Telefon",
    "client.email_placeholder": "E-Mail",
    "client.address_placeholder": "Adresse",
    
    "settings.title": "Einstellungen und Geschäftsinformationen",
    "settings.settings": "Einstellungen und Geschäftsinformationen",
    "settings.business_name": "Geschäftsname",
    "settings.phone": "Telefon",
    "settings.email": "E-Mail",
    "settings.address": "Adresse",
    "settings.website": "Webseite",
    "settings.default_tax": "Standard-Steuersatz %",
    "settings.default_markup": "Standard-Aufschlag %",
    "settings.footer": "Rechnungsfußzeilentext",
    "settings.invoice_footer": "Rechnungsfußzeilentext",
    "settings.logo": "Logo hochladen",
    "settings.upload_logo": "Logo hochladen",
    "settings.save": "Einstellungen speichern",
    "settings.language": "Sprache",
    "settings.invoice_template": "Rechnungsvorlage",
    "settings.saved": "Einstellungen gespeichert.",
    
    "template.choose_template": "Rechnungsvorlage Wählen",
    "template.choose_desc": "Klicken Sie auf eine Vorlage, um Ihre Rechnung in diesem Stil herunterzuladen.",
    
    "inventory.title": "Inventar",
    "inventory.inventory": "Bestandsverwaltung",
    "inventory.add_item": "Artikel hinzufügen",
    "inventory.item_name": "Artikelname",
    "inventory.description": "Beschreibung",
    "inventory.category": "Kategorie",
    "inventory.quantity": "Menge",
    "inventory.unit_type": "Einheitstyp",
    "inventory.unit_price": "Stückpreis ($)",
    "inventory.low_stock": "Niedrigbestandsschwelle",
    "inventory.total_value": "Gesamtbestandswert",
    "inventory.items_in_stock": "Artikel im Bestand",
    "inventory.save_item": "Artikel speichern",
    "inventory.delete": "Löschen",
    "inventory.no_items": "Noch keine Bestandsartikel",
    "inventory.add_first": "Fügen Sie Ihren ersten Artikel hinzu",
    
    "payments.title": "Zahlungen",
    "payments.payment_collection": "Zahlungseinzug",
    "payments.stripe_status": "Stripe Connect Status",
    "payments.active": "Aktiv",
    "payments.not_enabled": "Nicht aktiviert",
    "payments.connect_message": "Verbinden Sie Ihr Stripe-Konto, um Zahlungen von Rechnungen zu erhalten.",
    "payments.enable_button": "Zahlungseinzug aktivieren",
    "payments.enabling": "Aktivierung...",
    "payments.enabled_message": "Zahlungseinzug ist aktiviert. Sie können Zahlungslinks für Ihre Rechnungen generieren.",
    "payments.stats": "Zahlungsstatistiken",
    "payments.outstanding": "Ausstehend",
    "payments.paid_month": "Bezahlt (diesen Monat)",
    "payments.pending": "Ausstehend",
    "payments.how_it_works": "Wie es funktioniert",
    
    "referrals.referrals": "Empfehlungen – 20% auf Lebenszeit",
    "referrals.share": "Teilen Sie Ihren Link. Verdienen Sie 20% jeder monatlichen Zahlung aller, die Sie einbringen, solange sie abonniert bleiben.",
    "referrals.link": "Ihr Empfehlungslink",
    "referrals.copy": "Kopieren",
    "referrals.active": "Aktive Empfehlungen",
    "referrals.month": "Dieser Monat",
    "referrals.lifetime": "Lebenszeitgewinne",
    
    "pricing.choose_plan": "Wählen Sie Ihren Plan",
    "pricing.monthly": "Monatlich",
    "pricing.yearly": "Jährlich",
    "pricing.lifetime_early": "Lebenslang Early Bird",
    "pricing.lifetime_regular": "Lebenslang Regular",
    "pricing.per_month": "/Monat",
    "pricing.per_year": "/Jahr",
    "pricing.one_time": "Einmalzahlung",
    "pricing.trial_included": "7 Tage kostenlose Testversion inklusive!",
    "pricing.yearly_savings": "Sparen Sie $20/Jahr · 2 Monate gratis!",
    "pricing.monthly_desc": "Kostenlos für 7 Tage starten",
    "pricing.yearly_desc": "Bester Wert - sparen Sie 2 Monate",
    "pricing.first_500": "Nur die ersten 500",
    "pricing.spots_left": "Plätze verfügbar",
    "pricing.after_early": "Nach Early-Bird-Plätzen",
    "pricing.best_value": "BESTER WERT",
    "pricing.limited_offer": "BEGRENZTES ANGEBOT",
    "pricing.start_trial": "Kostenlose Testversion starten",
    "pricing.subscribe_now": "Jetzt abonnieren",
    "pricing.get_lifetime": "Lebenslangen Zugang erhalten",
    "pricing.feature_unlimited_invoices": "Unbegrenzte Rechnungen",
    "pricing.feature_unlimited_quotes": "Unbegrenzte Angebote",
    "pricing.feature_client_mgmt": "Kundenverwaltung",
    "pricing.feature_photos": "Fotoanhänge",
    "pricing.feature_branding": "Geschäftslogo & Branding",
    "pricing.feature_calculator": "Kostenrechner",
    "pricing.feature_download": "Rechnungsdownload (PNG)",
    "pricing.feature_all_forever": "Alle Funktionen für immer",
    "pricing.feature_no_fees": "Keine monatlichen Gebühren",
    "pricing.feature_priority": "Prioritäts-Support",
    "pricing.feature_updates": "Lebenslange Updates",
    "pricing.feature_early_access": "Früher Zugriff auf neue Funktionen",
    "pricing.feature_payment_included": "Zahlungseinzug inklusive",
    "pricing.addon_title": "Zahlungseinzug hinzufügen",
    "pricing.addon_notice": "Nur für Monats- und Jahrespläne verfügbar",
    "pricing.addon_stripe": "Stripe Connect Integration",
    "pricing.addon_desc": "Verbinden Sie Ihr Stripe-Konto, um Zahlungen direkt von Rechnungen einzuziehen",
    "pricing.referral_title": "Verdienen Sie 20% Provision",
    "pricing.referral_desc": "Empfehlen Sie Freunde und Kollegen an TradeBase und verdienen Sie 20% wiederkehrende Provision auf deren Abonnement. Je mehr Sie teilen, desto mehr verdienen Sie!",
    "pricing.referral_note": "Erhalten Sie Ihren Empfehlungslink nach der Anmeldung",
    "pricing.take_tour": "Tour machen",
    "pricing.tour_desc": "Alle Funktionen in Aktion mit Beispieldaten sehen",
    
    "trial.banner": "Kostenlos testen: X Tage verbleibend",
    "trial.subscribe_now": "Jetzt abonnieren",
    "tour.demo": "Sie sehen eine Demo mit Beispieldaten. Formulare sind deaktiviert.",
    "tour.exit": "Demo beenden und abonnieren",
    "tour.email_disabled": "E-Mail-Versand ist im Demo-Modus deaktiviert",
    "tour.convert_disabled": "Die Umwandlung von Angeboten ist im Demo-Modus deaktiviert",
    
    "quote.convert_to_invoice": "In Rechnung umwandeln",
    "quote.converted_success": "Angebot in Rechnung umgewandelt. Füllen Sie zusätzliche Details aus und speichern Sie.",
  },
  pt: {
    "common.back": "Voltar",
    "common.cancel": "Cancelar",
    
    "auth.login": "Entrar",
    "auth.signup": "Registrar",
    "auth.email": "Email",
    "auth.password": "Senha",
    "auth.create_account": "Criar Conta",
    "auth.forgot_password": "Esqueceu a senha?",
    "auth.view_pricing": "Ver Preços e Planos",
    
    "nav.dashboard": "Painel",
    "nav.new_invoice": "Nova Fatura",
    "nav.invoices": "Faturas",
    "nav.quotes": "Orçamentos",
    "nav.clients": "Clientes",
    "nav.payments": "Pagamentos",
    "nav.inventory": "Inventário",
    "nav.photos": "Fotos",
    "nav.calculator": "Calculadora de Custos",
    "nav.settings": "Configurações",
    "nav.referrals": "Indicações",
    
    "dashboard.new_invoice": "Nova Fatura",
    "dashboard.create_invoice": "Crie uma nova fatura com fotos e ajuda de custos.",
    "dashboard.invoiced_month": "Faturado este mês",
    "dashboard.paid_month": "Pago este mês",
    "dashboard.outstanding": "Saldo pendente",
    "dashboard.quotes": "Orçamentos",
    "dashboard.quotes_desc": "Rascunhe e acompanhe orçamentos de trabalhos.",
    "dashboard.clients": "Clientes",
    "dashboard.clients_desc": "Salve clientes uma vez, reutilize sempre.",
    "dashboard.photos": "Fotos",
    "dashboard.photos_desc": "Navegue em fotos de trabalhos por fatura.",
    "dashboard.invoices": "Faturas",
    "dashboard.invoices_desc": "Visualize e gerencie faturas anteriores.",
    "dashboard.payments": "Pagamentos",
    "dashboard.payments_desc": "Aceite pagamentos e acompanhe o status.",
    "dashboard.inventory": "Inventário",
    "dashboard.inventory_desc": "Acompanhe suprimentos, materiais e estoque.",
    "dashboard.calculator": "Calculadora",
    "dashboard.calculator_desc": "Materiais, horas, margem – pronto.",
    "dashboard.settings": "Configurações",
    "dashboard.settings_desc": "Logotipo, info empresarial, padrões.",
    "dashboard.referrals": "Indicações",
    "dashboard.referrals_desc": "Compartilhe seu link, ganhe 20% vitalício.",
    
    "invoice.invoice": "FATURA",
    "invoice.quote": "ORÇAMENTO",
    "invoice.invoice_number": "Fatura #",
    "invoice.quote_number": "Orçamento #",
    "invoice.date": "Data",
    "invoice.due_date": "Data de Vencimento",
    "invoice.client": "Faturar Para",
    "invoice.description": "Descrição",
    "invoice.quantity": "Qtd",
    "invoice.unit_price": "Preço Unitário",
    "invoice.total": "Total",
    "invoice.subtotal": "Subtotal",
    "invoice.tax": "Imposto",
    "invoice.amount_due": "Valor Devido",
    "invoice.notes": "Notas",
    "invoice.thank_you": "Obrigado pelo seu negócio!",
    "invoice.download": "Baixar",
    "invoice.send": "Enviar",
    "invoice.send_email": "Enviar e-mail",
    "invoice.email_modal_title": "Enviar fatura por e-mail",
    "invoice.recipient_email": "E-mail do destinatário",
    "invoice.recipient_name": "Nome do destinatário",
    "invoice.send_button": "Enviar fatura",
    "invoice.no_client_email": "Nenhum e-mail do cliente salvo - insira o endereço de e-mail",
    "invoice.email_sent_success": "Fatura enviada com sucesso!",
    "invoice.email_sent_error": "Falha ao enviar e-mail da fatura",
    "invoice.email_required": "O endereço de e-mail é obrigatório",
    "invoice.email_invalid": "Por favor, insira um endereço de e-mail válido",
    "invoice.client_placeholder": "Digite o nome do cliente ou selecione um cliente salvo",
    "invoice.notes_placeholder": "Notas opcionais para o cliente",
    "invoice.save_client": "Salvar como novo cliente",
    "invoice.invoices": "Faturas",
    "invoice.photos": "Fotos",
    "invoice.calculate": "Calcular",
    "invoice.tax_label": "Imposto",
    "invoice.save": "Salvar fatura",
    "invoice.new_invoice": "Nova fatura",
    
    "quote.quotes": "Orçamentos",
    "quote.new_quote": "+ Novo Orçamento",
    "quote.client_placeholder": "Digite o nome do cliente ou selecione um cliente salvo",
    "quote.notes_placeholder": "Notas opcionais para o cliente",
    "quote.date": "Data",
    "quote.line_items": "Itens de linha",
    "quote.add_item": "+ Adicionar item",
    "quote.subtotal": "Subtotal",
    "quote.tax": "Imposto",
    "quote.total": "Total",
    "quote.save": "Salvar orçamento",
    
    "client.clients": "Clientes",
    "client.add": "Adicionar cliente",
    "client.name_placeholder": "Nome do cliente",
    "client.phone_placeholder": "Telefone",
    "client.email_placeholder": "Email",
    "client.address_placeholder": "Endereço",
    
    "settings.title": "Configurações e Informações Comerciais",
    "settings.settings": "Configurações e Informações Comerciais",
    "settings.business_name": "Nome da Empresa",
    "settings.phone": "Telefone",
    "settings.email": "Email",
    "settings.address": "Endereço",
    "settings.website": "Site",
    "settings.default_tax": "Imposto Padrão %",
    "settings.default_markup": "Margem Padrão %",
    "settings.footer": "Texto de Rodapé da Fatura",
    "settings.invoice_footer": "Texto de Rodapé da Fatura",
    "settings.logo": "Carregar Logotipo",
    "settings.upload_logo": "Carregar Logotipo",
    "settings.save": "Salvar Configurações",
    "settings.language": "Idioma",
    "settings.invoice_template": "Modelo de Fatura",
    "settings.saved": "Configurações salvas.",
    
    "template.choose_template": "Escolher Modelo de Fatura",
    "template.choose_desc": "Clique em um modelo para baixar sua fatura nesse estilo.",
    
    "inventory.title": "Inventário",
    "inventory.inventory": "Gerenciamento de Inventário",
    "inventory.add_item": "Adicionar Item",
    "inventory.item_name": "Nome do Item",
    "inventory.description": "Descrição",
    "inventory.category": "Categoria",
    "inventory.quantity": "Quantidade",
    "inventory.unit_type": "Tipo de Unidade",
    "inventory.unit_price": "Preço Unitário ($)",
    "inventory.low_stock": "Limiar de Estoque Baixo",
    "inventory.total_value": "Valor Total do Inventário",
    "inventory.items_in_stock": "itens em estoque",
    "inventory.save_item": "Salvar Item",
    "inventory.delete": "Deletar",
    "inventory.no_items": "Sem itens de inventário ainda",
    "inventory.add_first": "Adicione Seu Primeiro Item",
    
    "payments.title": "Pagamentos",
    "payments.payment_collection": "Cobrança de Pagamentos",
    "payments.stripe_status": "Status do Stripe Connect",
    "payments.active": "Ativo",
    "payments.not_enabled": "Não Ativado",
    "payments.connect_message": "Conecte sua conta Stripe para começar a cobrar pagamentos de faturas.",
    "payments.enable_button": "Ativar cobrança de pagamentos",
    "payments.enabling": "Ativando...",
    "payments.enabled_message": "A cobrança de pagamentos está ativada. Você pode gerar links de pagamento para suas faturas.",
    "payments.stats": "Estatísticas de Pagamento",
    "payments.outstanding": "Pendente",
    "payments.paid_month": "Pago (Este Mês)",
    "payments.pending": "Aguardando",
    "payments.how_it_works": "Como Funciona",
    
    "referrals.referrals": "Indicações – 20% Por Vida",
    "referrals.share": "Compartilhe seu link. Ganhe 20% de cada pagamento mensal de todos que você trazer, enquanto permanecerem inscritos.",
    "referrals.link": "Seu link de indicação",
    "referrals.copy": "Copiar",
    "referrals.active": "Indicações ativas",
    "referrals.month": "Este mês",
    "referrals.lifetime": "Ganho vitalício",
    
    "pricing.choose_plan": "Escolha seu plano",
    "pricing.monthly": "Mensal",
    "pricing.yearly": "Anual",
    "pricing.lifetime_early": "Vitalício Early Bird",
    "pricing.lifetime_regular": "Vitalício Regular",
    "pricing.per_month": "/mês",
    "pricing.per_year": "/ano",
    "pricing.one_time": "pagamento único",
    "pricing.trial_included": "Teste grátis de 7 dias incluído!",
    "pricing.yearly_savings": "Economize $20/ano · 2 meses grátis!",
    "pricing.monthly_desc": "Comece grátis por 7 dias",
    "pricing.yearly_desc": "Melhor valor - economize 2 meses",
    "pricing.first_500": "Apenas os primeiros 500",
    "pricing.spots_left": "vagas restantes",
    "pricing.after_early": "Após as vagas early bird",
    "pricing.best_value": "MELHOR VALOR",
    "pricing.limited_offer": "OFERTA LIMITADA",
    "pricing.start_trial": "Iniciar teste grátis",
    "pricing.subscribe_now": "Inscrever-se agora",
    "pricing.get_lifetime": "Obter acesso vitalício",
    "pricing.feature_unlimited_invoices": "Faturas ilimitadas",
    "pricing.feature_unlimited_quotes": "Orçamentos ilimitados",
    "pricing.feature_client_mgmt": "Gestão de clientes",
    "pricing.feature_photos": "Anexos de fotos",
    "pricing.feature_branding": "Logo e marca empresarial",
    "pricing.feature_calculator": "Calculadora de custos",
    "pricing.feature_download": "Download de fatura (PNG)",
    "pricing.feature_all_forever": "Todos os recursos para sempre",
    "pricing.feature_no_fees": "Sem taxas mensais",
    "pricing.feature_priority": "Suporte prioritário",
    "pricing.feature_updates": "Atualizações vitalícias",
    "pricing.feature_early_access": "Acesso antecipado a novos recursos",
    "pricing.feature_payment_included": "Cobrança de pagamentos incluída",
    "pricing.addon_title": "Adicionar cobrança de pagamentos",
    "pricing.addon_notice": "Disponível apenas para planos Mensal e Anual",
    "pricing.addon_stripe": "Integração Stripe Connect",
    "pricing.addon_desc": "Conecte sua conta Stripe para cobrar pagamentos diretamente das faturas enviadas aos seus clientes",
    "pricing.referral_title": "Ganhe 20% de comissão",
    "pricing.referral_desc": "Indique amigos e colegas para o TradeBase e ganhe 20% de comissão recorrente na assinatura deles. Quanto mais você compartilha, mais você ganha!",
    "pricing.referral_note": "Obtenha seu link de indicação após se inscrever",
    "pricing.take_tour": "Fazer um tour",
    "pricing.tour_desc": "Ver todos os recursos em ação com dados de exemplo",
    
    "trial.banner": "Teste gratuito: X dias restantes",
    "trial.subscribe_now": "Inscrever-se Agora",
    "tour.demo": "Você está visualizando uma demonstração com dados de amostra. Formulários são desabilitados.",
    "tour.exit": "Sair da Demo e Inscrever-se",
    "tour.email_disabled": "O envio de e-mail está desabilitado no modo demonstração",
    "tour.convert_disabled": "A conversão de orçamentos está desabilitada no modo demonstração",
    
    "quote.convert_to_invoice": "Converter em fatura",
    "quote.converted_success": "Orçamento convertido em fatura. Preencha detalhes adicionais e salve.",
  }
};

let currentLanguage = localStorage.getItem('tradebase-language') || 'en';

function setLanguage(lang) {
  if (LANGUAGES[lang]) {
    currentLanguage = lang;
    localStorage.setItem('tradebase-language', lang);
    applyLanguage();
    return true;
  }
  return false;
}

function t(key) {
  return TRANSLATIONS[currentLanguage]?.[key] || TRANSLATIONS['en']?.[key] || key;
}

function applyLanguage() {
  // Update all elements with data-i18n attribute
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (el.tagName === 'INPUT' && el.type === 'submit') {
      el.value = t(key);
    } else if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
      el.placeholder = t(key);
    } else if (el.tagName === 'LABEL') {
      el.textContent = t(key);
    } else {
      el.textContent = t(key);
    }
  });
  
  // Update all elements with data-i18n-placeholder attribute
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    el.placeholder = t(key);
  });
}

// Apply language on load - ensure language is set from localStorage before translating
document.addEventListener('DOMContentLoaded', () => {
  setLanguage(currentLanguage); // This calls applyLanguage internally
});
