import { NextResponse } from "next/server";
import { z } from "zod";
import { ensureUserOrg } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { handleAIRequest, AiServiceError } from "@/lib/ai/handler";

export const dynamic = "force-dynamic";

const DISCLAIMER =
  "This information is generated by AI and may not reflect current local regulations. Always verify requirements with the local building authority.";

const outputSchema = z.object({
  permit_requirement: z.string(),
  permit_type: z.string().nullable().default(null),
  local_authority: z.object({
    office_name: z.string().nullable().default(null),
    phone: z.string().nullable().default(null),
    email: z.string().nullable().default(null),
    website: z.string().nullable().default(null),
  }),
  permit_process: z.array(z.string()).default([]),
  inspection_notes: z.array(z.string()).default([]),
  disclaimer: z.string().default(DISCLAIMER),
  needs_review: z.boolean().default(true),
});

export type PermitResult = z.infer<typeof outputSchema>;

export async function POST(req: Request) {
  const orgId = await ensureUserOrg();
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  const body = await req.json() as {
    description: string;
    address?: string;
    cityState?: string;
  };

  if (!body.description?.trim()) {
    return NextResponse.json({ error: "description is required" }, { status: 400 });
  }

  try {
    const { result, aiRunId } = await handleAIRequest({
      feature: "permit_assistant",
      orgId: orgId!,
      userId: user?.id,
      promptConfig: {
        role: "You are a construction permit assistant inside TradeBase, a contractor CRM. Your job is to provide practical permit guidance for contractors based on job description and location.",
        rules: [
          "Return valid JSON only — no markdown, no prose.",
          "Explain whether a permit is typically required based on the job and location.",
          "Identify the likely permit type if applicable.",
          "Provide likely local authority contact information if possible, otherwise use null.",
          "Summarize a likely permit process as an array of steps.",
          "Include inspection notes as an array of strings.",
          "Never present legal certainty — use language like 'typically', 'likely', 'in most jurisdictions'.",
          `Always set disclaimer to exactly: "${DISCLAIMER}"`,
          "Always set needs_review to true.",
          "Use null for any authority contact fields you cannot determine.",
        ],
        context: {
          job_description: body.description.trim(),
          ...(body.address ? { address: body.address } : {}),
          ...(body.cityState ? { city_state: body.cityState } : {}),
        },
        task: "Generate permit guidance for the job described, including permit requirement, type, local authority, process steps, and inspection notes.",
        schema: `{
  "permit_requirement": "plain-English verdict",
  "permit_type": "e.g. Building Permit, Mechanical Permit or null",
  "local_authority": { "office_name": "string or null", "phone": "string or null", "email": "string or null", "website": "string or null" },
  "permit_process": ["step string"],
  "inspection_notes": ["note string"],
  "disclaimer": "${DISCLAIMER}",
  "needs_review": true
}`,
      },
      input: body.description.trim(),
      schema: outputSchema,
      inputJson: { description: body.description, address: body.address, cityState: body.cityState },
      options: { maxTokens: 1000 },
    });

    return NextResponse.json({ ...result, ai_run_id: aiRunId });
  } catch (err) {
    if (err instanceof AiServiceError) {
      return NextResponse.json({ error: err.message }, { status: err.status });
    }
    return NextResponse.json({ error: "Internal error" }, { status: 500 });
  }
}
