import { NextResponse } from "next/server";
import { ensureUserOrg } from "@/lib/auth";
import { getOpenAIClient } from "@/lib/openai";

export async function POST(req: Request) {
  await ensureUserOrg();

  const body = await req.json();
  const { description, address, cityState } = body as {
    description: string;
    address?: string;
    cityState?: string;
  };

  if (!description?.trim()) {
    return NextResponse.json({ error: "description is required" }, { status: 400 });
  }

  const locationParts = [address, cityState].filter(Boolean).join(", ");
  const locationLine = locationParts ? `\nLocation: ${locationParts}` : "";

  const openai = getOpenAIClient();

  const completion = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    response_format: { type: "json_object" },
    max_completion_tokens: 1000,
    messages: [
      {
        role: "system",
        content: `You are a construction permit assistant helping contractors understand potential permit requirements.

Based on the job description and location provided, return a JSON object with exactly these keys:
- "permit_required": one of "Yes", "No", "Likely", or "Depends on scope"
- "permit_required_detail": 1-2 sentence explanation of why
- "permit_type": the type(s) of permit typically required (e.g. "Building Permit", "Mechanical Permit", "Electrical Permit", or "None")
- "local_authority": brief description of which authority typically handles this (e.g. "Local Building Department / City Hall")
- "relevant_codes": array of 2-4 relevant building code references as strings (e.g. "IRC Section R325 – Radon Control Methods")
- "inspection_notes": 1-2 sentences on what inspections are typically involved
- "disclaimer": always use this exact text: "This information is generated by AI and may not reflect current local regulations. Always verify requirements with the local building authority before starting work."

Do not present answers as legal advice. Be practical and concise.`,
      },
      {
        role: "user",
        content: `Job Description: ${description.trim()}${locationLine}`,
      },
    ],
  });

  const raw = completion.choices[0]?.message?.content ?? "{}";

  let result: Record<string, unknown>;
  try {
    result = JSON.parse(raw);
  } catch {
    return NextResponse.json({ error: "Failed to parse AI response" }, { status: 500 });
  }

  return NextResponse.json(result);
}
