import { NextResponse } from "next/server";
import { z } from "zod";
import { ensureUserOrg } from "@/lib/auth";
import { getOpenAIClient } from "@/lib/openai";
import { buildMessages } from "@/lib/ai/prompt";

const DISCLAIMER =
  "This information is generated by AI and may not reflect current local regulations. Always verify requirements with the local building authority.";

const localAuthoritySchema = z.object({
  office_name: z.string().nullable().default(null),
  phone: z.string().nullable().default(null),
  email: z.string().nullable().default(null),
  website: z.string().nullable().default(null),
});

const outputSchema = z.object({
  permit_requirement: z.string(),
  permit_type: z.string().nullable().default(null),
  local_authority: localAuthoritySchema,
  permit_process: z.array(z.string()).default([]),
  inspection_notes: z.array(z.string()).default([]),
  disclaimer: z.string().default(DISCLAIMER),
  needs_review: z.boolean().default(true),
});

export type PermitResult = z.infer<typeof outputSchema>;

export async function POST(req: Request) {
  await ensureUserOrg();

  const body = await req.json();
  const { description, address, cityState } = body as {
    description: string;
    address?: string;
    cityState?: string;
  };

  if (!description?.trim()) {
    return NextResponse.json({ error: "description is required" }, { status: 400 });
  }

  const schema = `{
  "permit_requirement": "plain-English verdict, e.g. 'A building permit is typically required for this work.'",
  "permit_type": "e.g. Building Permit, Mechanical Permit, Electrical Permit, or null",
  "local_authority": {
    "office_name": "e.g. City Building Department or null",
    "phone": "string or null",
    "email": "string or null",
    "website": "string or null"
  },
  "permit_process": [
    "Step-by-step process item string"
  ],
  "inspection_notes": [
    "Inspection note string"
  ],
  "disclaimer": "${DISCLAIMER}",
  "needs_review": true
}`;

  const messages = buildMessages(
    {
      role: "You are a construction permit assistant inside TradeBase, a contractor CRM. Your job is to provide practical permit guidance for contractors based on job description and location.",
      rules: [
        "Return valid JSON only — no markdown, no prose.",
        "Explain whether a permit is typically required based on the job and location.",
        "Identify the likely permit type if applicable.",
        "Provide likely local authority contact information if possible, otherwise use null.",
        "Summarize a likely permit process as an array of steps.",
        "Include inspection notes as an array of strings.",
        "Never present legal certainty — use language like 'typically', 'likely', 'in most jurisdictions'.",
        `Always set disclaimer to exactly: "${DISCLAIMER}"`,
        "Always set needs_review to true.",
        "Use null for any authority contact fields you cannot determine.",
      ],
      context: {
        job_description: description.trim(),
        ...(address ? { address } : {}),
        ...(cityState ? { city_state: cityState } : {}),
      },
      task: "Generate permit guidance for the job described, including permit requirement, type, local authority, process steps, and inspection notes.",
      schema,
    },
    description.trim()
  );

  const openai = getOpenAIClient();

  let raw: string;
  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      response_format: { type: "json_object" },
      max_completion_tokens: 1000,
      messages,
    });
    raw = completion.choices[0]?.message?.content ?? "{}";
  } catch (err) {
    console.error("OpenAI error:", err);
    return NextResponse.json({ error: "AI service unavailable" }, { status: 503 });
  }

  let result: PermitResult;
  try {
    result = outputSchema.parse(JSON.parse(raw));
  } catch {
    return NextResponse.json({ error: "Failed to parse AI response" }, { status: 500 });
  }

  return NextResponse.json(result);
}
