export type Contractor = {
  id: string;
  slug: string;
  name: string;
  trade: string;
  services: string[];
  tagline: string;
  description: string;
  location: string;
  city: string;
  distance: number;
  rating_google: number;
  reviews_google: number;
  rating_tb: number;
  reviews_tb: number;
  licensed: boolean;
  insured: boolean;
  emergency: boolean;
  verified: boolean;
  veteran_owned: boolean;
  years_in_business: number;
  jobs_completed: number;
  cover_color: string;
  cover_photo: string;
  project_photos: string[];
  avatar_color: string;
  lat: number;
  lng: number;
  featured: boolean;
  response_time: string;
};

export type Project = {
  id: string;
  contractor_id: string;
  contractor_slug: string;
  contractor_name: string;
  avatar_color: string;
  trade: string;
  title: string;
  location: string;
  photo: string;
  time_ago: string;
};

const U = (id: string, w = 600, h = 280) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;

export const CONTRACTORS: Contractor[] = [
  {
    id: "1",
    slug: "mike-sullivan-roofing",
    name: "Sullivan Roofing Co.",
    trade: "Roofing",
    services: ["Roof Replacement", "Roof Repair", "Gutters", "Skylights"],
    tagline: "Portland's most trusted roofer since 2003",
    description: "Family-owned roofing company with 20+ years serving the Portland metro. We specialize in asphalt shingle, metal roofing, and flat roofs. Free estimates always.",
    location: "Portland, OR",
    city: "Portland",
    distance: 1.2,
    rating_google: 4.9,
    reviews_google: 312,
    rating_tb: 4.8,
    reviews_tb: 47,
    licensed: true,
    insured: true,
    emergency: false,
    verified: true,
    veteran_owned: true,
    years_in_business: 21,
    jobs_completed: 1840,
    cover_color: "from-slate-700 to-slate-900",
    cover_photo: U("1582268611958-ebfd161ef9cf"),
    project_photos: [
      U("1568605114-ccfd63f70d8e", 120, 80),
      U("1570129477492-7b76ee02d73c", 120, 80),
      U("1558618666-fcd25c85cd64", 120, 80),
    ],
    avatar_color: "#1B3A6B",
    lat: 45.521,
    lng: -122.675,
    featured: true,
    response_time: "Usually responds in 2 hrs",
  },
  {
    id: "2",
    slug: "portland-electric",
    name: "Portland Electric Co.",
    trade: "Electrician",
    services: ["Panel Upgrades", "EV Chargers", "Wiring", "Lighting"],
    tagline: "Licensed electricians — same-day service available",
    description: "Full-service electrical contractor for residential and light commercial. Specializing in panel upgrades, EV charger installations, and smart home wiring.",
    location: "NE Portland, OR",
    city: "Portland",
    distance: 2.7,
    rating_google: 4.8,
    reviews_google: 198,
    rating_tb: 5.0,
    reviews_tb: 31,
    licensed: true,
    insured: true,
    emergency: true,
    verified: true,
    veteran_owned: false,
    years_in_business: 12,
    jobs_completed: 920,
    cover_color: "from-yellow-600 to-amber-800",
    cover_photo: U("1621905252507-b35492cc74b4"),
    project_photos: [
      U("1581094288338-2314dddb0f7b", 120, 80),
      U("1606760329800-74a6b1538ee6", 120, 80),
      U("1565814329452-e7fcdb4820a4", 120, 80),
    ],
    avatar_color: "#D97706",
    lat: 45.548,
    lng: -122.643,
    featured: true,
    response_time: "Usually responds in 1 hr",
  },
  {
    id: "3",
    slug: "pacific-plumbing",
    name: "Pacific Plumbing & Drain",
    trade: "Plumbing",
    services: ["Drain Cleaning", "Water Heaters", "Repiping", "Leak Repair"],
    tagline: "Fast, reliable plumbing — we stop leaks fast",
    description: "Licensed master plumber serving Portland and Beaverton. Specializing in drain cleaning, water heater replacement, and leak detection. 24/7 emergency calls welcome.",
    location: "Beaverton, OR",
    city: "Beaverton",
    distance: 5.3,
    rating_google: 4.7,
    reviews_google: 241,
    rating_tb: 4.7,
    reviews_tb: 28,
    licensed: true,
    insured: true,
    emergency: true,
    verified: true,
    veteran_owned: false,
    years_in_business: 9,
    jobs_completed: 1340,
    cover_color: "from-blue-700 to-blue-900",
    cover_photo: U("1603796846097-bee99e4a601f"),
    project_photos: [
      U("1585771724684-38269d6639fd", 120, 80),
      U("1552321554-5fefe8c9ef14", 120, 80),
      U("1556909172-8c2f746b8d72", 120, 80),
    ],
    avatar_color: "#1D4ED8",
    lat: 45.487,
    lng: -122.803,
    featured: false,
    response_time: "Usually responds in 3 hrs",
  },
  {
    id: "4",
    slug: "summit-hvac",
    name: "Summit HVAC & Comfort",
    trade: "HVAC",
    services: ["AC Install", "Furnace Repair", "Heat Pumps", "Air Quality"],
    tagline: "Year-round comfort for your home",
    description: "NATE-certified HVAC technicians serving Lake Oswego and surrounding areas. Expert installation of all major brands. Energy-efficient heat pump specialists.",
    location: "Lake Oswego, OR",
    city: "Lake Oswego",
    distance: 8.1,
    rating_google: 4.9,
    reviews_google: 156,
    rating_tb: 4.9,
    reviews_tb: 22,
    licensed: true,
    insured: true,
    emergency: false,
    verified: true,
    veteran_owned: true,
    years_in_business: 15,
    jobs_completed: 780,
    cover_color: "from-cyan-700 to-teal-900",
    cover_photo: U("1581094288338-2314dddb0f7b"),
    project_photos: [
      U("1558618047-3c95c7f0b8c4", 120, 80),
      U("1525785967-5e5bed3e3a92", 120, 80),
      U("1504307651254-35680f356dfd", 120, 80),
    ],
    avatar_color: "#0891B2",
    lat: 45.421,
    lng: -122.701,
    featured: false,
    response_time: "Usually responds in 4 hrs",
  },
  {
    id: "5",
    slug: "nw-painting-pros",
    name: "NW Painting Pros",
    trade: "Painting",
    services: ["Interior Painting", "Exterior Painting", "Cabinet Refinishing", "Deck Staining"],
    tagline: "Flawless finishes — on time, every time",
    description: "Professional residential painting with meticulous prep and premium materials. Interior and exterior specialists with a 2-year workmanship guarantee on all projects.",
    location: "SW Portland, OR",
    city: "Portland",
    distance: 3.4,
    rating_google: 4.6,
    reviews_google: 87,
    rating_tb: 4.8,
    reviews_tb: 19,
    licensed: true,
    insured: true,
    emergency: false,
    verified: false,
    veteran_owned: false,
    years_in_business: 6,
    jobs_completed: 430,
    cover_color: "from-purple-700 to-purple-900",
    cover_photo: U("1562259929-b4e1fd3aef09"),
    project_photos: [
      U("1589939018090-7b0f0d7b9a05", 120, 80),
      U("1558618666-fcd25c85cd64", 120, 80),
      U("1568605114-ccfd63f70d8e", 120, 80),
    ],
    avatar_color: "#7C3AED",
    lat: 45.497,
    lng: -122.695,
    featured: false,
    response_time: "Usually responds in 6 hrs",
  },
  {
    id: "6",
    slug: "concrete-masters-nw",
    name: "Concrete Masters NW",
    trade: "Concrete",
    services: ["Driveways", "Patios", "Foundations", "Stamped Concrete"],
    tagline: "Built to last — concrete work you can be proud of",
    description: "Decorative and structural concrete specialists for Portland homeowners. Driveways, patios, walkways, and exposed aggregate. 30-year family legacy.",
    location: "Gresham, OR",
    city: "Gresham",
    distance: 11.6,
    rating_google: 4.8,
    reviews_google: 124,
    rating_tb: 4.6,
    reviews_tb: 14,
    licensed: true,
    insured: true,
    emergency: false,
    verified: true,
    veteran_owned: false,
    years_in_business: 30,
    jobs_completed: 2100,
    cover_color: "from-stone-600 to-stone-800",
    cover_photo: U("1504307651254-35680f356dfd"),
    project_photos: [
      U("1501854140801-50d01698950b", 120, 80),
      U("1570129477492-7b76ee02d73c", 120, 80),
      U("1503708928676-1cb796a0891e", 120, 80),
    ],
    avatar_color: "#78716C",
    lat: 45.502,
    lng: -122.431,
    featured: false,
    response_time: "Usually responds in 1 day",
  },
  {
    id: "7",
    slug: "clean-gutter-co",
    name: "Clean Gutter Co.",
    trade: "Gutters",
    services: ["Gutter Cleaning", "Gutter Guards", "Downspout Repair", "Fascia"],
    tagline: "Keep water where it belongs",
    description: "Gutter cleaning, repair, and guard installation for Portland homes. Seasonal maintenance plans available. Fully insured. Same-week scheduling most of the year.",
    location: "Tigard, OR",
    city: "Tigard",
    distance: 6.8,
    rating_google: 4.7,
    reviews_google: 203,
    rating_tb: 4.5,
    reviews_tb: 38,
    licensed: false,
    insured: true,
    emergency: false,
    verified: false,
    veteran_owned: false,
    years_in_business: 4,
    jobs_completed: 610,
    cover_color: "from-green-700 to-emerald-900",
    cover_photo: U("1558618666-fcd25c85cd64"),
    project_photos: [
      U("1568605114-ccfd63f70d8e", 120, 80),
      U("1582268611958-ebfd161ef9cf", 120, 80),
      U("1570129477492-7b76ee02d73c", 120, 80),
    ],
    avatar_color: "#16A34A",
    lat: 45.431,
    lng: -122.771,
    featured: false,
    response_time: "Usually responds in 5 hrs",
  },
  {
    id: "8",
    slug: "cascade-tile-stone",
    name: "Cascade Tile & Stone",
    trade: "Tile & Flooring",
    services: ["Tile Installation", "Hardwood", "LVP Flooring", "Bathroom Remodel"],
    tagline: "Precision tile work for lasting beauty",
    description: "Award-winning tile and flooring installation with 15+ years of experience. Kitchens, bathrooms, showers, and custom mosaic work. Museum-quality finishes.",
    location: "NW Portland, OR",
    city: "Portland",
    distance: 4.1,
    rating_google: 5.0,
    reviews_google: 91,
    rating_tb: 5.0,
    reviews_tb: 11,
    licensed: true,
    insured: true,
    emergency: false,
    verified: true,
    veteran_owned: false,
    years_in_business: 16,
    jobs_completed: 890,
    cover_color: "from-rose-700 to-rose-900",
    cover_photo: U("1556909114-f6e7ad7d3136"),
    project_photos: [
      U("1552321554-5fefe8c9ef14", 120, 80),
      U("1556909172-8c2f746b8d72", 120, 80),
      U("1536566482680-fca31930a0bd", 120, 80),
    ],
    avatar_color: "#E11D48",
    lat: 45.533,
    lng: -122.700,
    featured: false,
    response_time: "Usually responds in 2 hrs",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "p1",
    contractor_id: "1",
    contractor_slug: "mike-sullivan-roofing",
    contractor_name: "Sullivan Roofing",
    avatar_color: "#1B3A6B",
    trade: "Roofing",
    title: "Full Roof Replacement",
    location: "SE Portland",
    photo: U("1582268611958-ebfd161ef9cf", 300, 200),
    time_ago: "2 days ago",
  },
  {
    id: "p2",
    contractor_id: "8",
    contractor_slug: "cascade-tile-stone",
    contractor_name: "Cascade Tile",
    avatar_color: "#E11D48",
    trade: "Tile & Flooring",
    title: "Master Bath Tile Remodel",
    location: "NW Portland",
    photo: U("1556909114-f6e7ad7d3136", 300, 200),
    time_ago: "4 days ago",
  },
  {
    id: "p3",
    contractor_id: "2",
    contractor_slug: "portland-electric",
    contractor_name: "Portland Electric",
    avatar_color: "#D97706",
    trade: "Electrician",
    title: "EV Charger + Panel Upgrade",
    location: "NE Portland",
    photo: U("1621905252507-b35492cc74b4", 300, 200),
    time_ago: "1 week ago",
  },
  {
    id: "p4",
    contractor_id: "6",
    contractor_slug: "concrete-masters-nw",
    contractor_name: "Concrete Masters",
    avatar_color: "#78716C",
    trade: "Concrete",
    title: "Stamped Concrete Patio",
    location: "Gresham",
    photo: U("1504307651254-35680f356dfd", 300, 200),
    time_ago: "1 week ago",
  },
  {
    id: "p5",
    contractor_id: "5",
    contractor_slug: "nw-painting-pros",
    contractor_name: "NW Painting Pros",
    avatar_color: "#7C3AED",
    trade: "Painting",
    title: "Whole-Home Exterior Paint",
    location: "SW Portland",
    photo: U("1562259929-b4e1fd3aef09", 300, 200),
    time_ago: "2 weeks ago",
  },
  {
    id: "p6",
    contractor_id: "3",
    contractor_slug: "pacific-plumbing",
    contractor_name: "Pacific Plumbing",
    avatar_color: "#1D4ED8",
    trade: "Plumbing",
    title: "Tankless Water Heater Install",
    location: "Beaverton",
    photo: U("1603796846097-bee99e4a601f", 300, 200),
    time_ago: "3 weeks ago",
  },
  {
    id: "p7",
    contractor_id: "4",
    contractor_slug: "summit-hvac",
    contractor_name: "Summit HVAC",
    avatar_color: "#0891B2",
    trade: "HVAC",
    title: "Heat Pump + Air Handler",
    location: "Lake Oswego",
    photo: U("1581094288338-2314dddb0f7b", 300, 200),
    time_ago: "3 weeks ago",
  },
  {
    id: "p8",
    contractor_id: "1",
    contractor_slug: "mike-sullivan-roofing",
    contractor_name: "Sullivan Roofing",
    avatar_color: "#1B3A6B",
    trade: "Roofing",
    title: "Metal Roof + Skylights",
    location: "Sellwood",
    photo: U("1570129477492-7b76ee02d73c", 300, 200),
    time_ago: "1 month ago",
  },
];

export const SERVICES = [
  "All Services",
  "Roofing",
  "Electrician",
  "Plumbing",
  "HVAC",
  "Painting",
  "Concrete",
  "Gutters",
  "Tile & Flooring",
  "Landscaping",
  "Carpentry",
  "Drywall",
  "Windows & Doors",
  "Pest Control",
  "Cleaning",
];

export const CITIES = [
  "Portland, OR",
  "Beaverton, OR",
  "Lake Oswego, OR",
  "Tigard, OR",
  "Gresham, OR",
  "Hillsboro, OR",
  "Vancouver, WA",
];
