// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homeowner-profile/Profile.tsx": () => import("../components/mockups/homeowner-profile/Profile.tsx"),
  "./components/mockups/admin-preview/Dashboard.tsx": () => import("../components/mockups/admin-preview/Dashboard.tsx"),
  "./components/mockups/admin-preview/Login.tsx": () => import("../components/mockups/admin-preview/Login.tsx")
};
